### ISSUE TITLE
habridge does not start

### ISSUE THREAD

**Issue by ChrisBeat** [bwssytems/ha-bridge#1081]
hello 

```
after the update to Libreele 9 and update of jave jre 1.8.211 the habridge does not start anymore and I get the following error message:

2019-04-24 19:12:57,358 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge startup sequence...
2019-04-24 19:12:57,404 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /storage/habridge/data/habridge.config
2019-04-24 19:12:58,135 [main] WARN  com.bwssystems.HABridge.BridgeSecurity - Cound not get security data, using default security (none): PBEWithMD5AndDES SecretKeyFactory not available
2019-04-24 19:12:58,137 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v5.2.2RC4) initializing....
Exception in thread "main" java.lang.InternalError: DMH.invokeSpecial_L3_L=Lambda(a0:L,a1:L,a2:L,a3:L)=>{
    t4:L=DirectMethodHandle.internalMemberName(a0:L);
    t5:L=MethodHandle.linkToSpecial(a1:L,a2:L,a3:L,t4:L);t5:L}
        at java.lang.invoke.MethodHandleStatics.newInternalError(MethodHandleStatics.java:127)
        at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:660)
        at java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(DirectMethodHandle.java:260)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:194)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:183)
        at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:89)
        at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:110)
        at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:115)
        at java.lang.invoke.Invokers.basicInvoker(Invokers.java:85)
        at java.lang.invoke.LambdaForm$NamedFunction.<init>(LambdaForm.java:1042)
        at java.lang.invoke.LambdaForm$Name.<init>(LambdaForm.java:1400)
        at java.lang.invoke.DelegatingMethodHandle.makeReinvokerForm(DelegatingMethodHandle.java:146)
        at java.lang.invoke.DelegatingMethodHandle.makeReinvokerForm(DelegatingMethodHandle.java:106)
        at java.lang.invoke.DelegatingMethodHandle.chooseDelegatingForm(DelegatingMethodHandle.java:92)
        at java.lang.invoke.DelegatingMethodHandle.<init>(DelegatingMethodHandle.java:44)
        at java.lang.invoke.MethodHandleImpl$IntrinsicMethodHandle.<init>(MethodHandleImpl.java:1331)
        at java.lang.invoke.MethodHandleImpl.makeIntrinsic(MethodHandleImpl.java:1373)
        at java.lang.invoke.MethodHandleImpl.makeArrays(MethodHandleImpl.java:1429)
        at java.lang.invoke.MethodHandleImpl.access$000(MethodHandleImpl.java:49)
        at java.lang.invoke.MethodHandleImpl$Lazy.<clinit>(MethodHandleImpl.java:610)
        at java.lang.invoke.MethodHandleImpl.varargsArray(MethodHandleImpl.java:1506)
        at java.lang.invoke.MethodHandleImpl.varargsArray(MethodHandleImpl.java:1623)
        at java.lang.invoke.MethodHandle.asCollector(MethodHandle.java:999)
        at java.lang.invoke.MethodHandleImpl$AsVarargsCollector.<init>(MethodHandleImpl.java:460)
        at java.lang.invoke.MethodHandleImpl$AsVarargsCollector.<init>(MethodHandleImpl.java:454)
        at java.lang.invoke.MethodHandleImpl.makeVarargsCollector(MethodHandleImpl.java:445)
        at java.lang.invoke.MethodHandle.setVarargs(MethodHandle.java:1325)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:1670)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethod(MethodHandles.java:1605)
        at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:781)
        at java.lang.invoke.CallSite.<clinit>(CallSite.java:226)
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
        at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
        at spark.Service.<init>(Service.java:90)
        at spark.Service.ignite(Service.java:102)
        at spark.Spark$SingletonHolder.<clinit>(Spark.java:51)
        at spark.Spark.getInstance(Spark.java:55)
        at spark.Spark.<clinit>(Spark.java:61)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:60)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at jdk.internal.org.objectweb.asm.ClassWriter.put(ClassWriter.java:1759)
        at jdk.internal.org.objectweb.asm.ClassWriter.addType(ClassWriter.java:1650)
        at jdk.internal.org.objectweb.asm.ClassWriter.addType(ClassWriter.java:1610)
        at jdk.internal.org.objectweb.asm.Frame.type(Frame.java:674)
        at jdk.internal.org.objectweb.asm.Frame.push(Frame.java:635)
        at jdk.internal.org.objectweb.asm.Frame.execute(Frame.java:1235)
        at jdk.internal.org.objectweb.asm.MethodWriter.visitMethodInsn(MethodWriter.java:922)
        at java.lang.invoke.InvokerBytecodeGenerator.emitStaticInvoke(InvokerBytecodeGenerator.java:867)
        at java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCodeBytes(InvokerBytecodeGenerator.java:715)
        at java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(InvokerBytecodeGenerator.java:618)
        at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:654)
        at java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(DirectMethodHandle.java:260)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:194)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:183)
        at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:89)

```

how can i fix it?

Regards 
ChrisBeat

**Comment by bwssytems** [comment]
Well, the error says you ran out of Java VM memory. What is the command line you are using start this?

**Comment by ChrisBeat** [comment]
The command line is

nohup java -jar -Dconfig.file=/storage/habridge/data/habridge.config /storage/habridge/ha-bridge-5.2.2RC4.jar > /storage/habridge/habridge-log.txt 2>&1 &

**Comment by bwssytems** [comment]
What are the system specs of the machine you are running this on as well?
