### ISSUE TITLE
Failing to load devices

### ISSUE THREAD

**Issue by marcfon** [bwssytems/ha-bridge#1165]
After doing an system update on my rasberry pi ha-bridge doesn't start properly anymore.

The web interface shows up but comes up with a 404 error related to loading devices.

This is the output of the log.
`2019-12-14 07:55:37,502 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge startup sequence...
2019-12-14 07:55:38,069 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v5.3.0) initializing....
2019-12-14 07:55:38,079 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /home/pi/habridge/data/habridge.config
2019-12-14 07:55:42,031 [main] INFO  spark.staticfiles.StaticFilesConfiguration - StaticResourceHandler configured with folder = /public
2019-12-14 07:55:42,093 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2019-12-14 07:55:42.255:INFO::Thread-0: Logging initialized @6656ms to org.eclipse.jetty.util.log.StdErrLog
2019-12-14 07:55:42,286 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - Initializing UDP response Socket...
2019-12-14 07:55:42,302 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - UDP response Socket initialized to: 50000
2019-12-14 07:55:42,320 [main] INFO  com.bwssystems.HABridge.plugins.http.HTTPHome - HTTP Home created.
2019-12-14 07:55:42,350 [main] INFO  com.bwssystems.HABridge.plugins.harmony.HarmonyHome - Harmony Home created. No Harmony devices configured.
2019-12-14 07:55:42,364 [main] INFO  com.bwssystems.HABridge.plugins.NestBridge.NestHome - Nest Home created.
2019-12-14 07:55:42,447 [main] INFO  com.bwssystems.nest.controller.NestSession - Starting Nest login...
2019-12-14 07:55:42,718 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
2019-12-14 07:55:42,719 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:8080
2019-12-14 07:55:42.742:INFO:oejs.Server:Thread-0: jetty-9.4.z-SNAPSHOT, build timestamp: 2017-11-21T22:27:37+01:00, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2019-12-14 07:55:42.933:INFO:oejs.session:Thread-0: DefaultSessionIdManager workerName=node0
2019-12-14 07:55:42.933:INFO:oejs.session:Thread-0: No SessionScavenger set, using defaults
2019-12-14 07:55:42.952:INFO:oejs.session:Thread-0: Scavenging every 660000ms
2019-12-14 07:55:43.093:INFO:oejs.AbstractConnector:Thread-0: Started ServerConnector@d47ae6{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-12-14 07:55:43.096:INFO:oejs.Server:Thread-0: Started @7507ms
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at com.google.gson.Gson.fromJson(Gson.java:765)
	at com.bwssystems.nest.controller.NestSession._login(NestSession.java:81)
	at com.bwssystems.nest.controller.NestSession.<init>(NestSession.java:67)
	at com.bwssystems.HABridge.plugins.NestBridge.NestHome.createHome(NestHome.java:190)
	at com.bwssystems.HABridge.plugins.NestBridge.NestHome.<init>(NestHome.java:40)
	at com.bwssystems.HABridge.HomeManager.buildHomes(HomeManager.java:62)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:92)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:388)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:209)
	... 10 more`

**Comment by craigski** [comment]
As this looks like a problem with the Nest interface, maybe you could try to disable in the habridge.config file and try a restart?

One other thought, have you recently migrated your Nest account to Google?

https://www.blog.google/products/google-nest/its-time-nest-users-can-now-switch-google-accounts/

**Comment by marcfon** [comment]
@craigski manually disable it in the json config?

And yes I've recently migrated... this is the first time I've restarted ha-bride since.
