### ISSUE TITLE
java.io.IOException: DNSIncoming corrupted message

### ISSUE THREAD

**Issue by bikeymouse** [bwssytems/ha-bridge#1205]
Hi, I'm running HA-Bridge in a docker container on an Raspberry PI which seems to work well.
However about every minute I get a the following error messages containing this:

```
2020-04-20T21:17:38.133483547Z  exception 
2020-04-20T21:17:38.133538079Z java.io.IOException: Received a message with the wrong length.
2020-04-20T21:17:38.133597090Z 	at javax.jmdns.impl.DNSIncoming.<init>(DNSIncoming.java:263)
2020-04-20T21:17:38.133654956Z 	at javax.jmdns.impl.SocketListener.run(SocketListener.java:50
2020-04-20T21:17:38.134232776Z 2020-04-20 23:17:38,125 [SocketListener(Philips-hue)] WARN  javax.jmdns.impl.SocketListener - SocketListener(Philips-hue).run() exception 
2020-04-20T21:17:38.134353975Z java.io.IOException: DNSIncoming corrupted message
2020-04-20T21:17:38.134430799Z 	at javax.jmdns.impl.DNSIncoming.<init>(DNSIncoming.java:268)
2020-04-20T21:17:38.134506738Z 	at javax.jmdns.impl.SocketListener.run(SocketListener.java:50)
2020-04-20T21:17:38.134568457Z Caused by: java.io.IOException: Received a message with the wrong length.
2020-04-20T21:17:38.134627416Z 	at javax.jmdns.impl.DNSIncoming.<init>(DNSIncoming.java:263)
2020-04-20T21:17:38.134688927Z 	... 1 common frames omitted
2020-04-20T21:17:38.137250576Z 2020-04-20 23:17:38,131 [SocketListener(Philips-hue)] WARN  javax.jmdns.impl.SocketListener - SocketListener(Philips-hue).run() exception 
2020-04-20T21:17:38.137376775Z java.io.IOException: DNSIncoming corrupted message
2020-04-20T21:17:38.137449693Z 	at javax.jmdns.impl.DNSIncoming.<init>(DNSIncoming.java:268)
2020-04-20T21:17:38.137517871Z 	at javax.jmdns.impl.SocketListener.run(SocketListener.java:50)
2020-04-20T21:17:38.137582091Z Caused by: java.io.IOException: Received a message with the wrong length.
2020-04-20T21:17:38.137640164Z 	at javax.jmdns.impl.DNSIncoming.<init>(DNSIncoming.java:263)
2020-04-20T21:17:38.137700946Z 	... 1 common frames omitted
```
(there is more info in the log if needed, but perhaps this already gives enough indication)

What could be the issue here?

**Comment by bwssytems** [comment]
It's just telling you ti is getting a bad MDNS message. It does not affect the operation of the ha-bridge.

**Comment by bikeymouse** [comment]
Ah, Ok thanks. But then I wonder what could be wrong if I get this every minute?

**Comment by bwssytems** [comment]
It is something on your network sending a DNS inquiry, the ha-bridge is just receiving it and saying it cannot deal with it. It is informational
