### ISSUE TITLE
Migration restoring device.db and habridge.config does not work (ha-bridge-5.4.0.jar)

### ISSUE THREAD

**Issue by ypoosn** [bwssytems/ha-bridge#1312]
Hi,

my setup up of a new ha-bridge instance and migrating the configuration files (device.db, habridge.config) does not work

Old setup is Java 1.8 with ha-bridge-5.4.0.jar
New setup is Java 1.8 with  ha-bridge-5.4.0.jar

`2021-05-08 20:11:18,616 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge startup sequence...
2021-05-08 20:11:19,067 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v5.4.0) initializing....
2021-05-08 20:11:19,073 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /home/openhabian/Packages/ha-bridge/data/habridge.config
2021-05-08 20:11:19,544 [main] WARN  com.bwssystems.HABridge.BridgeSettings - Issue loading values from file: file:///home/openhabian/Packages/ha-bridge/data/habridge.config, Gson convert failed. Using default settings.
2021-05-08 20:11:19,556 [main] INFO  com.bwssystems.HABridge.BridgeSettings - Adding 192.168.178.62 as our default upnp config address.
2021-05-08 20:11:19,632 [main] INFO  spark.staticfiles.StaticFilesConfiguration - StaticResourceHandler configured with folder = /public`

...

`2021-05-08 20:11:20,080 [main] INFO  com.bwssystems.HABridge.plugins.moziot.MozIotHome - Mozilla IOT Home created. No Mozilla IOTs configured.
2021-05-08 20:11:20,084 [main] INFO  com.bwssystems.HABridge.plugins.homegenie.HomeGenieHome - HomeGenie Home created. No HomeGenies configured.
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 2 path $
        at com.google.gson.Gson.fromJson(Gson.java:891)
        at com.google.gson.Gson.fromJson(Gson.java:844)
        at com.google.gson.Gson.fromJson(Gson.java:793)
        at com.google.gson.Gson.fromJson(Gson.java:765)
        at com.bwssystems.HABridge.dao.DeviceRepository._loadRepository(DeviceRepository.java:69)
        at com.bwssystems.HABridge.dao.DeviceRepository.<init>(DeviceRepository.java:56)
        at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.<init>(DeviceResource.java:51)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:94)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        ... 7 more
2021-05-08 20:11:20,205 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
2021-05-08 20:11:20,206 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:80  `

Starting ha-bridge creates the following output

The web interface throws several 404 errors:

![404 error habridge](https://user-images.githubusercontent.com/44301377/117541614-fd462800-b014-11eb-8c7f-bf4d8e05a250.JPG)

`May  8 16:08:19 GNE-OPENHAB3 java[28423]: 2021-05-08 16:08:19,025 [qtp27018591-12] INFO  spark.http.matching.MatcherFilter - The requested route [/api/devices/map/types] has not been mapped in Spark for Accept: [application/json, text/plain, */*]
May  8 16:08:19 GNE-OPENHAB3 java[28423]: 2021-05-08 16:08:19,089 [qtp27018591-16] INFO  spark.http.matching.MatcherFilter - The requested route [/api/devices] has not been mapped in Spark for Accept: [application/json, text/plain, */*]
May  8 16:08:19 GNE-OPENHAB3 java[28423]: 2021-05-08 16:08:19,091 [qtp27018591-24] INFO  spark.http.matching.MatcherFilter - The requested route [/api/devices/backup/available] has not been mapped in Spark for Accept: [application/json, text/plain, */*]
May2021-05-08 20:11:20,205 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
2021-05-08 20:11:20,206 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:802021-05-08 20:16:42,086 [qtp4097219-23] INFO  spark.http.matching.MatcherFilter - The requested route [/api/devices/map/types] has not been mapped in Spark for Accept: [application/json, text/plain, */*]
2021-05-08 20:16:42,142 [qtp4097219-13] INFO  spark.http.matching.MatcherFilter - The requested route [/api/devices] has not been mapped in Spark for Accept: [application/json, text/plain, */*]
2021-05-08 20:16:42,143 [qtp4097219-24] INFO  spark.http.matching.MatcherFilter - The requested route [/api/devices/backup/available] has not been mapped in Spark for Accept: [application/json, text/plain, */*]
2021-05-08 20:16:42,202 [qtp4097219-24] INFO  spark.http.matching.MatcherFilter - The requested route [/api] has not been mapped in Spark for Accept: [application/json, text/plain, */*]  8 16:08:19 GNE-OPENHAB3 java[28423]: 2021-05-08 16:08:19,141 [qtp27018591-24] INFO  spark.http.matching.MatcherFilter - The requested route [/api] has not been mapped in Spark for Accept: [application/json, text/plain, */*]`

Any idea?

best,

Ypo

**Comment by ypoosn** [comment]
Sorry, please ignore 

File transfer via Windows somehow messed up the config files. Direct sftp transfer raspi<->raspi solved it.

Best,,

Ypo
