### ISSUE TITLE
Has the Java dependency moved on from 8 to 11? :-(

### ISSUE THREAD

**Issue by mistyn8** [bwssytems/ha-bridge#1383]
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/bwssystems/HABridge/HABridge
has been compiled by a more recent version of the Java Runtime (class file version 55.0), 
this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
        ```

**Comment by mistyn8** [comment]
PS I'm trying to get this running on a DSM 6.2.4-25556 Update 6 , Synology DS212j with the ARM (Marvell Kirkwood 88F6281) so am limited to JAVA SE Embedded.

So can't update beyond 	ejdk-8u211-linux-arm-sflt.tar.gz
https://www.oracle.com/java/technologies/javaseembedded8u211-downloads.html

**Comment by mistyn8** [comment]
Doh.. 
https://github.com/bwssytems/ha-bridge/releases/tag/v5.4.1

both these are J11... 
- ha-bridge-5.4.1-java11.jar
- ha-bridge-v5.4.1.jar

**ha-bridge-5.4.1.jar** is the java 8 version!

I'd incorrectly assumed from the datestamp that the v5.4.1.jar was the one to plump for!
