### ISSUE TITLE
Cannot Link HA Bridge to Harmony Hub

### ISSUE THREAD

**Issue by hendryman** [bwssytems/ha-bridge#1387]
Using the Harmony iPad app, I try to add my HA Bridge to my Harmony Hub as a "Philips Hue Bridge"

On the iPad app, the message is:
`Philips Hu Bridge detected in your network.
Press the center button in the bridge to pair it with harmony hub.`

I've tried every single option I've found here on the issue tracker, including:
- Switched HA Bridge to "used link button" and pressed link button upon Harmony app requesting it
- Downgraded to various pre-5.x HA Bridge versions
- Switched off XMPP on the Harmony Hub
- Tried to add "Hunter Douglas" hub, then tried again to add the HA Bridge

I would be very thankful to for any lead on how to fix this as it drives me nuts : )

Error log attached.

```
Feb 25 09:32:06 raspberrypi java[31595]: 2023-02-25 09:32:06,601 [qtp5990440-35] ERROR spark.http.matching.GeneralError -
Feb 25 09:32:06 raspberrypi java[31595]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
Feb 25 09:32:06 raspberrypi java[31595]:         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
Feb 25 09:32:06 raspberrypi java[31595]:         at com.google.gson.Gson.fromJson(Gson.java:879)
Feb 25 09:32:06 raspberrypi java[31595]:         at com.google.gson.Gson.fromJson(Gson.java:844)
Feb 25 09:32:06 raspberrypi java[31595]:         at com.google.gson.Gson.fromJson(Gson.java:793)
Feb 25 09:32:06 raspberrypi java[31595]:         at com.google.gson.Gson.fromJson(Gson.java:765)
Feb 25 09:32:06 raspberrypi java[31595]:         at com.bwssystems.HABridge.plugins.hue.HueInfo.getHueDeviceInfo(HueInfo.java:136)
Feb 25 09:32:06 raspberrypi java[31595]:         at com.bwssystems.HABridge.plugins.hue.HueHome.getHueDeviceInfo(HueHome.java:88)
Feb 25 09:32:06 raspberrypi java[31595]:         at com.bwssystems.HABridge.hue.HueMulator.lightsListHandler(HueMulator.java:930)
Feb 25 09:32:06 raspberrypi java[31595]:         at com.bwssystems.HABridge.hue.HueMulator.lambda$setupServer$23(HueMulator.java:304)
Feb 25 09:32:06 raspberrypi java[31595]:         at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
Feb 25 09:32:06 raspberrypi java[31595]:         at spark.http.matching.Routes.execute(Routes.java:61)
Feb 25 09:32:06 raspberrypi java[31595]:         at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
Feb 25 09:32:06 raspberrypi java[31595]:         at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.server.Server.handle(Server.java:530)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
Feb 25 09:32:06 raspberrypi java[31595]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
Feb 25 09:32:06 raspberrypi java[31595]:         at java.lang.Thread.run(Thread.java:745)
Feb 25 09:32:06 raspberrypi java[31595]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
Feb 25 09:32:06 raspberrypi java[31595]:         at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:388)
Feb 25 09:32:06 raspberrypi java[31595]:         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:209)
Feb 25 09:32:06 raspberrypi java[31595]:         ... 28 common frames omitted
```

**Comment by guy1958** [comment]
Do you have the "Unique ID to use 9 Octets" box checked under the Bridge Control tab?

**Comment by hendryman** [comment]
@guy1958 : thanks for the tip, but trying it did not change things... any other ideas?

**Comment by guy1958** [comment]
Does the bridge get discovered ok with Alexa (assuming you have Alexa)? It's mainly designed for use with Alexa and might not necessarily work with other systems that support Philips Hue.

**Comment by hendryman** [comment]
No, it doesn't get discovered by Alexa either.

**Comment by guy1958** [comment]
Then try saving (renaming) your db file and start with a blank configuration. Add just a simple, single device and see if you can detect that. I do see some type of error message at the top of the log in your first post, but it's incomplete. It should start up cleanly to begin with.

**Comment by hendryman** [comment]
Deleting the db worked. Thank you very much for your kind support!
