### ISSUE TITLE
Nest login broken?

### ISSUE THREAD

**Issue by marcfon** [bwssytems/ha-bridge#161]
The Nest login is throwing an exception (on 3.1.0). Is anyone else having this issue?

`2016-09-07 12:13:13,523 [main] INFO  com.bwssystems.nest.controller.NestSession - Starting Nest login...
2016-09-07 12:13:13,837 [qtp10183850-25] DEBUG spark.webserver.MatcherFilter - httpMethod:get, uri: /api/57344036db8d4b6ba6243c2d6aad03ff/lights
2016-09-07 12:13:14,431 [qtp10183850-28] DEBUG spark.webserver.MatcherFilter - httpMethod:get, uri: /description.xml
2016-09-07 12:13:16,203 [main] DEBUG com.bwssystems.nest.controller.NestSession - _login Response: <<REMOVED JSON FOR GITHUB POST BECAUSE OF LENGTH>>
2016-09-07 12:13:16,221 [main] INFO  com.bwssystems.nest.controller.NestSession - Completed Nest login...
2016-09-07 12:13:16,251 [main] DEBUG com.bwssystems.nest.controller.Nest - getting status: https://czfe18-front01-iad01.transport.home.nest.com/v2/mobile/user.2700076
2016-09-07 12:13:16,470 [qtp10183850-29] DEBUG spark.webserver.MatcherFilter - httpMethod:get, uri: /description.xml
2016-09-07 12:13:16,924 [main] DEBUG com.bwssystems.nest.controller.Nest - status response: <<REMOVED JSON FOR GITHUB POST BECAUSE OF LENGTH>>
Exception in thread "main" com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:917)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:917)
	at com.bwssystems.nest.protocol.status.StructureDeserializer.deserialize(StructureDeserializer.java:23)
	at com.bwssystems.nest.protocol.status.StructureDeserializer.deserialize(StructureDeserializer.java:14)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at com.google.gson.Gson.fromJson(Gson.java:765)
	at com.bwssystems.nest.controller.Nest._getStatus(Nest.java:54)
	at com.bwssystems.nest.controller.Nest.<init>(Nest.java:45)
	at com.bwssystems.NestBridge.NestHome.<init>(NestHome.java:38)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:68)
`

**Comment by seanford** [comment]
Do you have any Nest Protects?

**Comment by marcfon** [comment]
> Do you have any Nest Protects?

No just a single Nest Thermostat (3rd generation).

**Comment by seanford** [comment]
Ok, I had the same error (XML parsing error) with Nest integration as well.  I think issue is still open.
I just stopped using the Bridge for Nest and went with the Native Nest/Echo integration and it has been fine since.

**Comment by bwssytems** [comment]
This is still puzzling to me as my nests still work properly even with protects

**Comment by seanford** [comment]
Any way to create an option to dump the raw replies from Nest to a file BEFORE they are processed as part of the next version?  I tried to sniff the Network traffic, but it is an HTTPS session and I don’t have the time to dump keys, etc. to decrypt it.  Would be useful for all HTTP traffic debugging in general, not just Nest.

**Comment by marcfon** [comment]
Just a wild guess here. Could it have something to do with the fact that I have have two nest thermostats linked to my account?

**Comment by seanford** [comment]
I do as well.

**Comment by bwssytems** [comment]
The account I use I have 2 thermos and 2 protects. I still need to do that special debug version for you both

**Comment by bwssytems** [comment]
@marcfon Could you drop your logfile in to paste.bin and send me the link. The debug output is being cutoff here by github and I need to see the json string that is being returned.

Thanks

**Comment by bwssytems** [comment]
@marcfon Thanks for the log file. I did find that the json layout of the Structure object is different in your response, I'll need to take a look at how to determine the difference.

**Comment by bwssytems** [comment]
So, I tested it standalone with the data you provided and I couldn't get it to fail. Since the error is occurring on an object vs primitive in the StructureDetail, I am commenting out any variable that is not needed. Hopefully that will help.... Less is more....

**Comment by bwssytems** [comment]
try this jar to see if it does anything different as there are mods for areas that may help.

http://bwssystems.com/files/ha-bridge-v3.1.0a.jar

**Comment by marcfon** [comment]
The link to the file is incorrect.

**Comment by bwssytems** [comment]
I have an updated jar to try: http://bwssystems.com/files/ha-bridge-3.1.0b.jar

**Comment by marcfon** [comment]
The login with 3.1.0b version works. At first the nest devices didn't show up in the Nest panel but after 20-30s they did. Now I'm just trying to figure out how to set the temperature through ha-bridge :)

**Comment by bwssytems** [comment]
Awesome! glad that issue got fixed. Use the nest helper tab to build nest temp control devices. Then it is "alexa, set Living room to 72"


I have an updated jar to try: http://bwssystems.com/files/ha-bridge-3.1.0c.jar

**Comment by bwssytems** [comment]
I have an updated jar to try: http://bwssystems.com/files/ha-bridge-3.1.0d.jar

**Comment by marcfon** [comment]
What is there to test in the new jar? So I can tell you if it works :)

**Comment by bwssytems** [comment]
Making sure Alexa still find the hub, the last versions had issues with different apps.
