### ISSUE TITLE
Bridge Crashes trying to operate command

### ISSUE THREAD

**Issue by heffneil** [bwssytems/ha-bridge#168]
Here is the output from the Terminal sessions when running the bridge.  This has happened numerous times for some reason.  Hopefully the output below can help rectify the issue.

2016-09-17 22:37:54,626 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.1.0) starting....
2016-09-17 22:37:54,661 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
2016-09-17 22:37:54,769 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.1.0) initializing....
2016-09-17 22:37:54,788 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2016-09-17 22:37:54,953 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
2016-09-17 22:37:54.955:INFO::Thread-0: Logging initialized @1333ms
2016-09-17 22:37:55,105 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2016-09-17 22:37:55,107 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:8080
2016-09-17 22:37:55.112:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2016-09-17 22:37:55.198:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@67ccf195{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-09-17 22:37:55.199:INFO:oejs.Server:Thread-0: Started @1585ms
2016-09-17 22:37:55,441 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
2016-09-17 22:37:55,454 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
2016-09-17 22:37:55,458 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
2016-09-17 22:37:55,472 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener running and ready....
2016-09-18 00:02:14,323 [main] ERROR com.bwssystems.HABridge.upnp.UpnpListener - UpnpListener encountered an error sending upnp response packet. Shutting down
java.io.IOException: Host is down
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at com.bwssystems.HABridge.upnp.UpnpListener.sendUpnpResponse(UpnpListener.java:219)
	at com.bwssystems.HABridge.upnp.UpnpListener.startListening(UpnpListener.java:138)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:86)
2016-09-18 00:02:15,326 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener - ended, error found
2016-09-18 00:02:15,346 [main] INFO  spark.webserver.JettySparkServer - >>> Spark shutting down ...
2016-09-18 00:02:15.353:INFO:oejs.ServerConnector:main: Stopped ServerConnector@67ccf195{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-09-18 00:02:15,355 [main] INFO  spark.webserver.JettySparkServer - done
2016-09-18 00:02:15,355 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.1.0) exiting....

**Comment by bwssytems** [comment]
Interesting error. It looks like another device sent a upnp discovery and when the ha-bridge tried to send a response to that ip address, that device was not responding. In this case the ha-bridge should just log a warning. I'll put in an enhancement.

**Comment by heffneil** [comment]
Does it say what IP address was making the request? I don't see it but I am curious what else might be looking on my network?  I have an echo and a Tap.  The Echo works poorly on the network but the Tap is very good - strange.
