### ISSUE TITLE
Unexpected termination

### ISSUE THREAD

**Issue by cherowley** [bwssytems/ha-bridge#177]
Hi!

After askking alexa to discover new devices this morning I found that the HA bridge software had stopped during it. The HA Bridge had been running great since Saturday..

The log:

>>>
2016-10-03 10:58:58,705 [qtp412560-15] INFO  com.bwssystems.HABridge.hue.HueMulator - Traceupnp: hue lights list requested: ab8786fd7adb40f9a5ddf4a93300509f from 192.168.2.150
2016-10-03 10:59:05,097 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message.
2016-10-03 10:59:05,097 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true
2016-10-03 10:59:05,097 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - Traceupnp: SSDP packet from 192.168.2.105:12607, body: M-SEARCH * HTTP/1.1
MX: 5
ST: upnp:rootdevice
MAN: "ssdp:discover"
User-Agent: UPnP/1.0 DLNADOC/1.50 Kodi
Connection: close
Host: 239.255.255.250:1900

2016-10-03 10:59:05,097 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - Traceupnp: sendUpnpResponse discovery template with address: 192.168.2.100 and port: 8080
2016-10-03 10:59:05,097 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - Traceupnp: discoveryResponse is <<<HTTP/1.1 200 OK
CACHE-CONTROL: max-age=86400
EXT:
LOCATION: http://192.168.2.100:8080/description.xml
SERVER: FreeRTOS/7.4.2 UPnP/1.0 IpBridge/1.10.0
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:2f402f80-da50-11e1-9b23-001788102201::urn:schemas-upnp-org:device:basic:1

>>>
2016-10-03 10:59:05,141 [main] ERROR com.bwssystems.HABridge.upnp.UpnpListener - UpnpListener encountered an error sending upnp response packet. Shutting down
java.io.IOException: Operation not permitted
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at com.bwssystems.HABridge.upnp.UpnpListener.sendUpnpResponse(UpnpListener.java:259)
	at com.bwssystems.HABridge.upnp.UpnpListener.startListening(UpnpListener.java:170)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:86)
2016-10-03 10:59:06,204 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener - ended, error found
2016-10-03 10:59:06,322 [main] INFO  spark.webserver.JettySparkServer - >>> Spark shutting down ...
2016-10-03 10:59:06.350:INFO:oejs.ServerConnector:main: Stopped ServerConnector@77ffc2{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-10-03 10:59:06,351 [main] INFO  spark.webserver.JettySparkServer - done
2016-10-03 10:59:06,352 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.1.0d) exiting....

I was installing/removing some packages on the synology at the time so wondered if that caused the problem - I'll keep an eye on it :)

**Comment by bwssytems** [comment]
Yes, it looks like the synology recycled the network subsystem and the ha-bridge did not have a valid port any more. That would be an expected error as it needs to be restarted.

**Comment by cherowley** [comment]
Thanks buddy :)
