### ISSUE TITLE
Lost bridge when changed port

### ISSUE THREAD

**Issue by stas1000** [bwssytems/ha-bridge#244]
I changed the bridge port through the web interface to 80 but not i cannot access it anymore when tupying the web address in the browser using the original 8080 or 80. not sure if there is a way i can search for where it has gone?

On the bridge terminal it says listening on 0.0.0.0:80

**Comment by bwssytems** [comment]
How is your system setup on what type of device and what is the ip of that device?

**Comment by stas1000** [comment]
The ip is 192.168.0.12 and it is setup up on a qnap nas running on ubuntu through terminal

via Newton Mail<https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.1.18&pv=6.0&source=email_footer_2>
On Wed, Nov 16, 2016 at 12:50am, BWS Systems <notifications@github.com<mailto:notifications@github.com>> wrote:


How is your system setup on what type of device and what is the ip of that device?

**Comment by bwssytems** [comment]
Still not sure what is wrong as the bridge says it is listening on all interfaces. This sounds like os setup issues and I'm not familiar with this setup.

**Comment by stas1000** [comment]
i used to login by going to 192.168.0.12:8080. i then changed web server portr under bridge control from 8080 to 80- and hit save.
now i can no longer get to the web interface using 192.168.0.12:8080 or 192.168.0.12:80.

would the best bet be to refresh ubuntu and re-install everything from fresh?

**Comment by stas1000** [comment]
admin@ubuntu_1604:~$ java -jar ha-bridge-3.2.2.jar
2016-11-15 23:19:02,183 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.2.2) starting....
2016-11-15 23:19:02,211 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
2016-11-15 23:19:02,366 [main] WARN  com.bwssystems.HABridge.BridgeSettings - The upnp config address, 192.168.0.99, does not match any known IP's on this host.
2016-11-15 23:19:02,367 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2016-11-15 23:19:02,408 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2016-11-15 23:19:02.637:INFO::Thread-0: Logging initialized @1180ms
2016-11-15 23:19:02,840 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2016-11-15 23:19:02,844 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:80
2016-11-15 23:19:02.850:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2016-11-15 23:19:02,971 [Thread-0] ERROR spark.webserver.JettySparkServer - ignite failed
java.net.SocketException: Permission denied
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:326)
    at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
    at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.server.Server.doStart(Server.java:384)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at spark.webserver.JettySparkServer.ignite(JettySparkServer.java:131)
    at spark.SparkInstance.lambda$init$0(SparkInstance.java:341)
    at java.lang.Thread.run(Thread.java:745)

**Comment by bwssytems** [comment]
Well this says it all:

2016-11-16 18:34:25,879 [Thread-0] INFO spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:80
2016-11-16 18:34:25.887:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2016-11-16 18:34:26,015 [Thread-0] ERROR spark.webserver.JettySparkServer - ignite failed
**java.net.SocketException: Permission denied**

You either have some other webserver running on port 80 or you do not have access to port 80. Google this to help you on QNAP as this has been discussed before.

**Comment by fauna5** [comment]
I suspect you are running this as a user. Ports under 1000 are only allowed to be opened by root. Either change the port to something like 8081 or run the program as root

**Comment by stas1000** [comment]
Is there a guide on how to do this? As i am unable to acces the web interface

Cheers

On Thu, Nov 17, 2016 at 10:01am, Rich Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


I suspect you are running this as a user. Ports under 1000 are only allowed to be opened by root. Either change the port to something like 8081 or run the program as root

**Comment by fauna5** [comment]
To run as root: start the program with sudo. E.g. "sudo ./starthabridge.sh"

To change the port, add a command line flag. It is detailed in the README.
