### ISSUE TITLE
Firmware update on Harmony created issue?

### ISSUE THREAD

**Issue by oliverdesouza** [bwssytems/ha-bridge#246]
After updating my Hub, I seem to run into a problem. See below
C:\HA-Bridge>java -jar -Dharmony.address=192.168.0.216 -Dharmony.user=xxxxxxx@gmail.com -Dharmony.pwd=xxxxx ha-bridge-3.2.2.jar
2016-11-17 20:38:06,915 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.2.2) starting....
2016-11-17 20:38:06,946 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
2016-11-17 20:38:07,165 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2016-11-17 20:38:07,212 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2016-11-17 20:38:07.380:INFO::Thread-0: Logging initialized @1090ms
2016-11-17 20:38:07,505 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2016-11-17 20:38:07,505 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:8080
2016-11-17 20:38:07.505:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2016-11-17 20:38:07,818 [main] INFO  com.bwssystems.harmony.HarmonyServer - setup initiated ....
2016-11-17 20:38:07.865:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@2a3414e7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-11-17 20:38:07.865:INFO:oejs.Server:Thread-0: Started @1585ms
2016-11-17 20:38:09,771 [main] ERROR com.bwssystems.harmony.HarmonyHome - Cannot get harmony client (default) setup, Exiting with message: Failed to parse response from Logitech auth service
java.lang.RuntimeException: Failed to parse response from Logitech auth service
        at net.whistlingfish.harmony.protocol.AuthService.getLoginToken(AuthService.java:45)
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:111)
        at com.bwssystems.harmony.HarmonyServer.execute(HarmonyServer.java:78)
        at com.bwssystems.harmony.HarmonyServer.setup(HarmonyServer.java:50)
        at com.bwssystems.harmony.HarmonyHome.<init>(HarmonyHome.java:45)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:68)
Caused by: us.monoid.json.JSONException: JSONObject["GetUserAuthTokenResult"] is not a JSONObject.
        at us.monoid.json.JSONObject.getJSONObject(JSONObject.java:579)
        at net.whistlingfish.harmony.protocol.AuthService.getLoginToken(AuthService.java:41)
        ... 5 common frames omitted
2016-11-17 20:38:09,787 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started....
2016-11-17 20:38:09,818 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
2016-11-17 20:38:09,834 [main] INFO  com.bwssystems.util.UDPDatagramSender - Initializing UDP response Seocket...
2016-11-17 20:38:09,834 [main] INFO  com.bwssystems.util.UDPDatagramSender - UDP response Seocket initialized to: 50000
2016-11-17 20:38:10,037 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
2016-11-17 20:38:10,068 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
2016-11-17 20:38:10,209 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener running and ready....

The IP, User and password is correct. Any idea what could have happened? The App on my phone works fine.

**Comment by bwssytems** [comment]
Interesting, I'll need to see what version my hub is running.

**Comment by digiltd** [comment]
Same here

**Comment by JustinFarris** [comment]
I'm seeing the same error, though I didn't consciously update the firmware on my hub. It might have phoned home by itself.

**Comment by ITGuruWoo** [comment]
I think I am seeing the same issue. Just added a new Activity and did not appear in bridge. Reintialised and now getting Cannot get harmony client (HarHubLounge) setup, Exiting with message: Failed to parse response from Logitech auth service

**Comment by jlekhter** [comment]
What version is the hub? I'm on 4.11.6 but still using 3.2.0 of the bridge and all is well so far.

**Comment by bwssytems** [comment]
I get it now too. This sucks, will debug.

**Comment by bwssytems** [comment]
That bad thing is, it is the authorization URL which is returning this. Looking on the web, but don't see any issues with other systems hooking up to harmony yet. I have tested this outside of the bridge and it fails as well.

**Comment by bwssytems** [comment]
So, the best thing is... my home production system has authenticated days ago and is still valid and working. I will not be bouncing that anytime soon....

**Comment by oliverdesouza** [comment]
Well. I hope you can crack this. I **love** running HABridge. If it no longer works with Harmony, I won't know what to do with my Harmony hubs. I'm kinda hooked on having Alexa do things for me. 
Echo already supports Harmony but it only recognizes activities. I hate activities cos it can only run one activity at a time.

**Comment by bwssytems** [comment]
Well, What I need to crack this is to look at the new message the hub sends for authentication. The firmware on the hub is working properly and that was updated, but it's local API works the same.

**Comment by michaelhinchey** [comment]
I'm having issues as well.  
   Tried adding a second harmony hub and I'm getting errors when trying to do any harmony activity inside of the bridge and alexa.  I'm running the older Bridge 3.1.2  and 4172 on echo and 564186420 on echo dot.  I was really hoping to test out how the second harmony hub works on the bridge since the harmony skill only works with one harmony hub.  Just my luck.  
   Well here's to you finding a cure doc.... Good luck and thank you.

**Comment by timforsyth** [comment]
Hi,

Just to confirm, I'm a developer of a couple of android / wear apps, and my own library is having the same issue with the Logitech web service.

A few people are talking about this on other forums but no resolution yet.

The web service always results null:

{
    "GetUserAuthTokenResult": null
}

The hub is still accepting tokens that are cached, I think the token is just a hash of your email and some key as it doesn't seem to change.

**Comment by bwssytems** [comment]
Yes, with some other posts I have put out, there may be a solution on how to get back into the hub. This site uses a pair method with the hub that extracts the token. https://github.com/swissmanu/harmonyhubjs-client

**Comment by timforsyth** [comment]
Hi,

Yeah, I saw that earlier, I'm going to try out the method=pair request
tonight when I get home with my own library.

Let me know if it works for you, likewise, I'll share my findings too.

thanks,
Tim.

**Comment by audiofreak9** [comment]
Don't forget until the bridge gets figured out, Alexa now has a native Harmony Skill.  It's not as good as the options provided by the ha-bridge, but it's better than nothing.

**Comment by bristolbaz** [comment]
`Don't forget until the bridge gets figured out, Alexa now has a native Harmony Skill. It's not as good as the options provided by the ha-bridge, but it's better than nothing.`

Not in the UK they don't!  Missing my Alexa integration and having to use the remote is a PITA!!

**Comment by michaelhinchey** [comment]
And they also do not allow for a secondary harmony hub.

**Comment by bwssytems** [comment]
New method with local pair works fine in my test bed. Also, no need for login info of username/password.

**Comment by bwssytems** [comment]
Fixed!

**Comment by bristolbaz** [comment]
Thank you - all my harmony activities and devices are back!

but...

I get this error if I try and switch any of them

> SyntaxError: Unexpected token < in JSON at position 0

**Comment by bwssytems** [comment]
@bristolbaz I cannot re-create your JSON issue

**Comment by bristolbaz** [comment]
Sorry, my bad.  I had renamed some of my harmony hubs earlier when I was trying to get it to work and this had caused the error.

Thanks again.

**Comment by michaelhinchey** [comment]
How did you get it back?  I still don't have anything except for a few harmony devices that I already configured.  Did you have to reprogram something.  Thx in advance for the info.

**Comment by bristolbaz** [comment]
@michaelhinchey  update to 3.5.0

**Comment by michaelhinchey** [comment]
I have updated to 3.5.  I forgot to edit the nssm.  Then I was adding a
second harmony elite w/ hub and had some issues.  Looks like I had to
change some things on my account that may have broke the link between the
bridge and my first harmony hub.  I had to delete what I had already and
start over.  It seems to be working correctly now.  Thank you.
  I am having issues with the harmony skill because they require
authentication I believe.  The harmony on one account has a different email
account attached to it.  But that is a whole nother story.  I'll get that
sorted out with them on Monday.






         Every dream is a goal with a date on it; if you can conceive it
believe it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"
