### ISSUE TITLE
harmony 

### ISSUE THREAD

**Issue by smithski** [bwssytems/ha-bridge#255]
Now the username and password options are deprecated and not available in the browser interface, how do you configure authentication to the harmony hub?

Since installing 3.5.0 I get the following and can no longer connect to harmony:

ERROR com.bwssystems.harmony.HarmonyHome - Cannot get harmony client (Harmony Hub) setup, Exiting with message: Failed communicating with Harmony Hub
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:179)
        at com.bwssystems.harmony.HarmonyServer.execute(HarmonyServer.java:78)
        at com.bwssystems.harmony.HarmonyServer.setup(HarmonyServer.java:50)
        at com.bwssystems.harmony.HarmonyHome.<init>(HarmonyHome.java:45)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:70)
Caused by: org.jivesoftware.smack.SmackException$ConnectionException: null
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:433)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:808)
        at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:396)
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:115)
        ... 4 common frames omitted

**Comment by bwssytems** [comment]
It does not need the username password as it is using the local pair option. Make sure you have the correct IP address of your hub in the bridge control configuration.

**Comment by smithski** [comment]
yeah - thanks, I hadn't realised but the harmony received a new DHCP address - now reserved!
