### ISSUE TITLE
Nest account linked- JsonSyntaxException:

### ISSUE THREAD

**Issue by smithski** [bwssytems/ha-bridge#266]
Hi - after adding Nest thermostat to my home today and attempting to link to the bridge. Authenticates OK but not happy with something ...

2016-11-22 22:19:16,869 [main] INFO  com.bwssystems.nest.controller.NestSession - Starting Nest login...
2016-11-22 22:19:18,409 [main] INFO  com.bwssystems.nest.controller.NestSession - Completed Nest login...
Exception in thread "main" com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:917)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        at com.google.gson.Gson.fromJson(Gson.java:944)
        at com.google.gson.Gson.fromJson(Gson.java:917)
        at com.bwssystems.nest.protocol.status.DeviceDeserializer.deserialize(DeviceDeserializer.java:23)
        at com.bwssystems.nest.protocol.status.DeviceDeserializer.deserialize(DeviceDeserializer.java:14)
        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        at com.google.gson.Gson.fromJson(Gson.java:844)
        at com.google.gson.Gson.fromJson(Gson.java:793)
        at com.google.gson.Gson.fromJson(Gson.java:765)
        at com.bwssystems.nest.controller.Nest._getStatus(Nest.java:54)
        at com.bwssystems.nest.controller.Nest.<init>(Nest.java:45)
        at com.bwssystems.NestBridge.NestHome.<init>(NestHome.java:38)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:72)

thanks.

**Comment by bwssytems** [comment]
Will need to investigate. Had this kind of issue before due to a status reply that cannot be deserialized.

**Comment by bwssytems** [comment]
I will be removing some decoding that is not needed in the nest deserializer.

**Comment by p2dewit** [comment]
NEST integration still has issues on V4.0.0 Beta. Authentication seems to work but after that bridge seems to crash and looses all devices.

**Comment by bwssytems** [comment]
If you could post your beta version and the error message that  would help.

**Comment by p2dewit** [comment]
With 4Beta4 version.
After save (after adding Nest userid and password) re-initializing does not return.

2017-01-22 19:59:00,151 [main] INFO  com.bwssystems.nest.controller.NestSession - Starting Nest login...
2017-01-22 19:59:02,177 [main] INFO  com.bwssystems.nest.controller.NestSession - Completed Nest login...
Exception in thread "main" java.lang.NullPointerException
        at com.bwssystems.nest.controller.Nest._getStatus(Nest.java:55)
        at com.bwssystems.nest.controller.Nest.<init>(Nest.java:45)
        at com.bwssystems.HABridge.plugins.NestBridge.NestHome.createHome(NestHome.java:173)
        at com.bwssystems.HABridge.plugins.NestBridge.NestHome.<init>(NestHome.java:37)
        at com.bwssystems.HABridge.HomeManager.buildHomes(HomeManager.java:39)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:68)

**Comment by ersan** [comment]
I'm now having this problem after updating from 3.5.1 to 4.2.0

`2017-03-02 11:09:55,764 [main] INFO  com.bwssystems.nest.controller.NestSession - Starting Nest login...
2017-03-02 11:09:57,606 [main] INFO  com.bwssystems.nest.controller.NestSession - Completed Nest login...
Exception in thread "main" java.lang.NullPointerException
        at com.bwssystems.nest.protocol.status.DeviceDeserializer.deserialize(DeviceDeserializer.java:26)
        at com.bwssystems.nest.protocol.status.DeviceDeserializer.deserialize(DeviceDeserializer.java:13)
        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        at com.google.gson.Gson.fromJson(Gson.java:844)
        at com.google.gson.Gson.fromJson(Gson.java:793)
        at com.google.gson.Gson.fromJson(Gson.java:765)
        at com.bwssystems.nest.controller.Nest._getStatus(Nest.java:54)
        at com.bwssystems.nest.controller.Nest.<init>(Nest.java:45)
        at com.bwssystems.HABridge.plugins.NestBridge.NestHome.createHome(NestHome.java:181)
        at com.bwssystems.HABridge.plugins.NestBridge.NestHome.<init>(NestHome.java:37)
        at com.bwssystems.HABridge.HomeManager.buildHomes(HomeManager.java:42)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:68)
`

**Comment by bwssytems** [comment]
will take a look

**Comment by bwssytems** [comment]
This is due to not having any Rooms or Locations setup for your nest. I am updating the nest controller to handles this situations better.
