### ISSUE TITLE
Manually added devices throw syntax error

### ISSUE THREAD

**Issue by d3dc** [bwssytems/ha-bridge#268]
I'm using the latest release (3.5.1).

I've just setup a new user, and added a systemctl service for ha-bridge.

I added my first device:
```json
{
"id":"1",
"uniqueid":"00:17:88:5E:D3:01-01",
"name":"Living Room Light",
"deviceType":"exec",
"targetDevice":"Encapsulated",
"offUrl":"echo \"rf p5 off\" | nc localhost 1099",
"dimUrl":"echo \"rf p5 xdim ${intensity.percent}\" | nc localhost 1099",
"onUrl":"echo \"rf p5 on\" | nc localhost 1099"
}
```
If I tell my Home to turn on that device, nothing happens.

When I click any test buttons - e.g "Test ON" - in the web console, I get an alert:
> SyntaxError: Unexpected token < in JSON at position 0

I get a similar error if I do a `PUT` to the api interface:
> Unexpected '<'

In all cases, the log only shows:
```
ERROR		spark.webserver.MatcherFilter
```

What's going on?

EDIT:

Server stack trace:
```
2016-11-23 20:39:20,382 [qtp1382067100-16] ERROR spark.webserver.MatcherFilter - 
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 18 path $[0].item
	at com.google.gson.Gson.fromJson(Gson.java:894)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at com.google.gson.Gson.fromJson(Gson.java:765)
	at com.bwssystems.HABridge.hue.HueMulator.lambda$19(HueMulator.java:916)
	at spark.RouteImpl$1.handle(RouteImpl.java:58)
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 18 path $[0].item
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:495)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:418)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	... 22 common frames omitted

```

**Comment by bwssytems** [comment]
So, just use the tcp:// calls to port 1099. Much easier and it works fine with Mochad.

**Comment by d3dc** [comment]
tcp works great for mochad!

But, I still have scripts I want to run. That device might have been a bad example.

I'm still not able to get the `Execute Script/Program` device type to work. I tried just a simple device like:
```
  {
    "id": "16",
    "uniqueid": "00:17:88:5E:D3:10-10",
    "name": "Test Device",
    "deviceType": "exec",
    "targetDevice": "Encapsulated",
    "offUrl": "touch ~/off",
    "dimUrl": "touch ~/dim_${intensity}",
    "onUrl": "touch ~/on",
    "deviceState": ...
  }
```

**Comment by bwssytems** [comment]
The special characters are throwing this off. The Script/Program is meant to execute a filesystem script or program. Write your commands in a shell script and then call that from the ha-bridge.

**Comment by bwssytems** [comment]
Did you get this resolved?

**Comment by cketcham** [comment]
I also got a similar crash while setting up hue lights to pass through to my hue hub:

    2016-12-03 17:17:55,092 [qtp2047300257-37] ERROR spark.webserver.MatcherFilter - 
    com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 14 path $[0].item
    	at com.google.gson.Gson.fromJson(Gson.java:894)
    	at com.google.gson.Gson.fromJson(Gson.java:844)
    	at com.google.gson.Gson.fromJson(Gson.java:793)
    	at com.google.gson.Gson.fromJson(Gson.java:765)
    	at com.bwssystems.HABridge.hue.HueMulator.lambda$setupServer$20(HueMulator.java:776)
    	at spark.RouteImpl$1.handle(RouteImpl.java:58)
    	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
    	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
    	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
    	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    	at org.eclipse.jetty.server.Server.handle(Server.java:517)
    	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
    	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
    	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 14 path $[0].item
    	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
    	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:495)
    	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:418)
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
    	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    	at com.google.gson.Gson.fromJson(Gson.java:879)
    	... 22 common frames omitted
   
It started working when I built v3.5.1 rather than master.

**Comment by bwssytems** [comment]
Yes, master is not the same as the tag v3.5.1... I checked some new things into that branch that are not fully tested, sorry. You can also download the pre compiled jar in the release area

**Comment by cketcham** [comment]
That's ok, just wanted to make sure you were aware of the bug.

**Comment by bwired-nl** [comment]
i have the same problem when adding a mqtt message
SyntaxError: Unexpected token < in JSON at position 0

this is what is do
topic: command/ctx35
message: {"housecode":"J", "devicecode":"01", "command":"ON"}

this generates:
[{"clientId":"testb","topic":"command/ctx35","message":"{"housecode":"J", "devicecode":"01", "command":"ON"}"}]

if I test the bridge device "TEST ON' Button i get
SyntaxError: Unexpected token < in JSON at position 0

tried all kind of formats....
the json validator tell me no good json, but a valid jason give the same
probably my input is wrong?

**Comment by bwssytems** [comment]
The issue is with the current handling of JSON within JSON. The next version, 4.0.0 will handle this properly. The OP had problems with trying to run commands that are script commands on a command line. Open up a new issue with problem please. Thanks

**Comment by janningnetworks** [comment]
Same problem. just installed 3.5.1. added device: but everytime i click on the "Test-Button" i get the "SyntaxError: Unexpected token < in JSON at position 0"

same problem with 3.2.2




just want to call a url

**Comment by bwssytems** [comment]
@janningnetworks You issue is not the same, as it is an encoding error. Did you copy and paste the construct from another website? You may have encoded characters in your string.

**Comment by janningnetworks** [comment]
No, I tried it several Times. Even, if i change the URL to something like:
http://Google.de the Error appears. I recreated. the Bridge, now it works
for the device. Cannot reproduce the Error right now.

Am 28.12.2016 8:55 nachm. schrieb "BWS Systems" <notifications@github.com>:

@janningnetworks <https://github.com/janningnetworks> You issue is not the
same, as it is an encoding error. Did you copy and paste the construct from
another website? You may have encoded characters in your string.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bwssytems/ha-bridge/issues/268#issuecomment-269531499>,
or mute the thread

**Comment by pr3sidentspence** [comment]
@d3dc wrote:
> tcp works great for mochad!

Can you specify how this works? I'm just moving this stuff over from testing on Windows (with x10 commander as the x10 handler) to Linux with mochad. I've tried:

tcp://127.0.0.1:1099/rf%20a1%20on

With nothing working. But I don't know what, if anything, any of the other fields should be.

**Comment by audiofreak9** [comment]
If MOCHAD and he ha-bridge are on the same LINUX box, then you should be calling MOCHAD commands using "Execute Script/Program" config Type in the ha-bridge.  All you enter in the On/Dim/Off input for the MOCHAD command is "pl A1 on" for power line commands, or "rf A1 on" for radio frequency commands.

**Comment by pr3sidentspence** [comment]
Just that? Not echo "rf a1 on" | nc localhost 1099 ?

I made livingroomon.sh and put the above in it. Ringing it from client
works. I get errors when trying to get ha-bridge to run the script.

Using "/home/pi/habridge/livingroomon.sh" as my on command.

Ok, I went back to release and it works now with my shell scripts.

**Comment by audiofreak9** [comment]
Yeah, I messed up my first reply (treating it like HEYU), I edited my last comment to be exactly that: 
`echo "rf a1 on" | nc localhost 1099` my mistake.

**Comment by audiofreak9** [comment]
You can skip the shell script "livingroomon.sh" and just enter the `echo "rf a1 on" | nc localhost 1099` right into the ha-bridge.

**Comment by pr3sidentspence** [comment]
Hmmm, when I did that it wasn't working. Do you need to escape the quotes like the OP did in their example?

**Comment by audiofreak9** [comment]
Give escaping a try, I am not fully familiar with how quotes in the input would be treated when posted to the device.db file, but escaped quotes won't hurt.

**Comment by bwssytems** [comment]
Actually, the TCP way is much cleaner and is not affected by the process handling.
Also set the map type to "tcpDevice" and the device  type to "TCP" in the device
Try this in your on URL: [{"item":"tcp://127.0.01:1099/rf a1 on"},"type":"tcpDevice"]

**Comment by pr3sidentspence** [comment]
I went back to 3.5.1, I don't see tcpDevice under map, and the URL you provide gives the JSON syntax error in 3.5.1.  I will try that out later, but at the moment, I finally have everything I wanted working in 3.5.1. I used shell scripts to sent api commands to "rooms" with curl.

**Comment by bwssytems** [comment]
@pr3sidentspence  Sorry, that is not in 3.5.1. make sure the map type is blank and the device type is TCP and that will work.
