### ISSUE TITLE
Save Settings Problem

### ISSUE THREAD

**Issue by mhbosch** [bwssytems/ha-bridge#27]
Hello,

i use the Version 1.2.3 (on Ubunut Server with Oracle Java V8). When i add a Device and restart the Server, the devices are lost.

By save i beome the follow mistake:

[qtp1847669615-27] ERROR spark.webserver.MatcherFilter -
java.lang.NullPointerException
        at java.nio.file.Files.provider(Files.java:97)
        at java.nio.file.Files.notExists(Files.java:2434)
        at com.bwssystems.HABridge.dao.DeviceRepository.repositoryWriter(DeviceRepository.java:101)
        at com.bwssystems.HABridge.dao.DeviceRepository.save(DeviceRepository.java:78)
        at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.lambda$1(DeviceResource.java:79)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)

Where can i solve the Problem?

**Comment by bwssytems** [comment]
What is the directory you are running the bridge from?

Are you also giving the argument -Ddevice.db=<something> and what is the something?

**Comment by mhbosch** [comment]
Thanks for the quick answer.

I have made a mistkae with the permission. Now i have start the server with root permission.
The server have made a device.db and save the settings.
:-)

First tries a sucessfully!

**Comment by bwssytems** [comment]
Great, glad it's fixed.
