### ISSUE TITLE
Can't find Harmony Hub ?

### ISSUE THREAD

**Issue by dmb0058** [bwssytems/ha-bridge#279]
Hi,

I'm getting an odd error ... all looks the same as usual (same logitech username/password, harmony hub has the usual ip address etc.). Clicking the Test On button gives "Request Error, Pleae look in your habridge log: error {"type":6,"address":"/lights/4","description":"Should not get here, no harmony hub available","parameter":"/lights/4state"}". Harmony app works fine from tablets etc.
When I look in the log file as suggested I see the errors below.

Cheers,

David

2016-11-26 18:43:55,698 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /data/habridge/habridge.
config
2016-11-26 18:44:04,073 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2016-11-26 18:44:06,199 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2016-11-26 18:44:31.783:INFO::Thread-0: Logging initialized @38040ms
2016-11-26 18:44:38,258 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2016-11-26 18:44:38,430 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:8080
2016-11-26 18:44:38.676:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2016-11-26 18:44:42.487:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@574b75{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-11-26 18:44:42.494:INFO:oejs.Server:Thread-0: Started @48886ms
2016-11-26 18:44:50,597 [main] INFO  com.bwssystems.harmony.HarmonyServer - setup initiated ....
2016-11-26 18:45:00,016 [main] ERROR com.bwssystems.harmony.HarmonyHome - Cannot get harmony client (Harmony Hub) setup, Exiting
 with message: Failed to parse response from Logitech auth service
java.lang.RuntimeException: Failed to parse response from Logitech auth service
        at net.whistlingfish.harmony.protocol.AuthService.getLoginToken(AuthService.java:45)
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:111)
        at com.bwssystems.harmony.HarmonyServer.execute(HarmonyServer.java:78)
        at com.bwssystems.harmony.HarmonyServer.setup(HarmonyServer.java:50)
        at com.bwssystems.harmony.HarmonyHome.<init>(HarmonyHome.java:45)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:68)
Caused by: us.monoid.json.JSONException: JSONObject["GetUserAuthTokenResult"] is not a JSONObject.
        at us.monoid.json.JSONObject.getJSONObject(JSONObject.java:579)
        at net.whistlingfish.harmony.protocol.AuthService.getLoginToken(AuthService.java:41)
        ... 5 common frames omitted
2016-11-26 18:45:00,396 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management servic
e started....
2016-11-26 18:45:00,644 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
2016-11-26 18:45:00,697 [main] INFO  com.bwssystems.util.UDPDatagramSender - Initializing UDP response Seocket...
2016-11-26 18:45:00,732 [main] INFO  com.bwssystems.util.UDPDatagramSender - UDP response Seocket initialized to: 50000
2016-11-26 18:45:03,355 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
2016-11-26 18:45:03,558 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
2016-11-26 18:45:03,571 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener running and ready....
2016-11-26 20:37:35.819:WARN:oejh.HttpParser:qtp559290-12: bad HTTP parsed: 400 Bad URI for HttpChannelOverHttp@182c643{r=1,c=fa
lse,a=IDLE,uri=-}
2016-11-26 20:43:17.379:WARN:oejh.HttpParser:qtp559290-17: bad HTTP parsed: 400 Bad URI for HttpChannelOverHttp@1eb9702{r=1,c=fa
lse,a=IDLE,uri=-}
2016-11-26 20:43:17.448:WARN:oejh.HttpParser:qtp559290-15: bad HTTP parsed: 400 Bad URI for HttpChannelOverHttp@964b22{r=1,c=fal
se,a=IDLE,uri=-}
2016-11-26 20:43:17.504:WARN:oejh.HttpParser:qtp559290-12: bad HTTP parsed: 400 Bad URI for HttpChannelOverHttp@102fe8f{r=1,c=fa
lse,a=IDLE,uri=-}
2016-11-27 01:19:58,000 [qtp559290-24] WARN  com.bwssystems.HABridge.hue.HueMulator - Should not get here, no harmony hub availa
ble
2016-11-27 01:20:15,852 [qtp559290-16] WARN  com.bwssystems.HABridge.hue.HueMulator - Should not get here, no harmony hub availa
root@x10:/var/log/heyu#
2016-11-27 09:45:40.333:WARN:oejh.HttpParser:qtp559290-15: bad HTTP parsed: 400 Bad URI for HttpChannelOverHttp@311265{r=1,c=fal
se,a=IDLE,uri=-}
2016-11-27 09:48:01.772:WARN:oejh.HttpParser:qtp559290-14: bad HTTP parsed: 400 Bad URI for HttpChannelOverHttp@17e6a06{r=1,c=fa
lse,a=IDLE,uri=-}
2016-11-27 10:25:29,952 [qtp559290-29] WARN  com.bwssystems.HABridge.hue.HueMulator - Should not get here, no harmony hub availa
ble
2016-11-27 10:25:32,950 [qtp559290-15] WARN  com.bwssystems.HABridge.hue.HueMulator - Should not get here, no harmony hub availa
ble
2016-11-27 12:59:03,510 [qtp559290-16] WARN  com.bwssystems.HABridge.hue.HueMulator - Should not get here, no harmony hub availa
ble
root@x10:/var/log/heyu#

**Comment by jlekhter** [comment]
This was fixed in the latest release. Harmony changed the way you connect to it. Use the 3.5.1 version of the bridge and it should work.

**Comment by dmb0058** [comment]
Excellent, works perfectly, thanks.
