### ISSUE TITLE
TLS Version for HTTP calls

### ISSUE THREAD

**Issue by jasondharper** [bwssytems/ha-bridge#332]
Is there a way to force outbound HTTP calls on an manual activity to use TLS v1.2?  I have an endpoint I'm trying to connect to that only supports that version.  Works fine from Postman but after debugging habridge, I'm pretty sure the issue is related to SSL Version:

 at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        ... 35 common frames omitted

**Comment by bwssytems** [comment]
I'll take a look. I am using the default Java ssl handler currently.

**Comment by jasondharper** [comment]
Sweet.  Thanks man!

**Comment by bwssytems** [comment]
Well, this is having issues, testing this with another item and it is failing for https
