### ISSUE TITLE
Trying to run the habridge on my QNAP

### ISSUE THREAD

**Issue by hmspain** [bwssytems/ha-bridge#35]
The habridge.sh file looks like:

[/share/habridge] # more habridge.sh
java -jar -Dvera.address=192.168.1.91 -Dserver.port=8081 -Dupnp.response.port=55000 -Dupnp.config.address=192.168.1.203 -Dupnp.strict=false -Dvtwo.compatibility=true -Dtrace.upnp=false -Dharmony.address=192.168.1.105 -Dharmony.user=xxxxxx -Dharmony.pwd=xxxxxx -Dnest.user=xxxxxx -Dnest.pwd=xxxxxx /share/habridge/ha-bridge-1.3.0.jar 2>&1 | tee /share/habridge/habridge.log &
[/share/habridge] #

The log file looks like:

[/share/habridge] # ./habridge.sh
[/share/habridge] #
[/share/habridge] # [main] INFO com.bwssystems.HABridge.HABridge - HA Bridge (v1.3.0) starting setup....
[main] INFO com.bwssystems.harmony.HarmonyServer - setup initiated ....
[main] INFO com.bwssystems.harmony.HarmonyServer - activity changed: [-1] PowerOff
[main] INFO com.bwssystems.nest.controller.NestSession - Starting Nest login...
[main] INFO com.bwssystems.nest.controller.NestSession - Completed Nest login...
[main] INFO com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started....
[main] INFO com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
[main] INFO com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
2016-01-30 06:07:18.061:INFO::Thread-5: Logging initialized @4033ms
[Thread-5] INFO spark.webserver.JettySparkServer - == Spark has ignited ...
[Thread-5] INFO spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:8081
2016-01-30 06:07:18.108:INFO:oejs.Server:Thread-5: jetty-9.3.z-SNAPSHOT
[Thread-5] ERROR spark.webserver.JettySparkServer - ignite failed
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:326)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:384)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at spark.webserver.JettySparkServer.ignite(JettySparkServer.java:131)
        at spark.SparkInstance.lambda$init$0(SparkInstance.java:341)
        at java.lang.Thread.run(Thread.java:745)

**Comment by hmspain** [comment]
I think I have the solution...  changed my script to:

lsof -i:8082 | grep "8082" | awk '{print $2}' | xargs kill
lsof -i:50002 | grep "50002" | awk '{print $2}' | xargs kill
java -jar -Dvera.address=192.168.1.91 -Dserver.port=8082 -Dupnp.response.port=50002 -Dupnp.config.address=192.168.1.203 -Dupnp.strict=false -Dvtwo.compatibility=true -Dtrace.upnp=false -Dharmony.address=192.168.1.105 -Dharmony.user=xxxxxx -Dharmony.pwd=xxxxxx -Dnest.user=xxxxxx -Dnest.pwd=xxxxxx /share/habridge/ha-bridge-1.3.0.jar 2>&1 | tee /share/habridge/habridge.log &

**Comment by bwssytems** [comment]
The error "java.net.BindException: Address already in use" lets you know that a port is in use by another program. It seems you have fixed it by changing the port. Closing this out.
