### ISSUE TITLE
Suddenly web control panel not showing up.

### ISSUE THREAD

**Issue by narcosi** [bwssytems/ha-bridge#368]
This site can’t be reached

192.168.20.24 refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

I restarted my Pi today and this happend

I have no idea why this would sudenly happen. vnc is working on that IP so its a network problem.

any ideas?

thanks

here is my log:

2017-01-17 17:30:43,726 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.5.1) starting....
2017-01-17 17:30:43,770 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from system properties
2017-01-17 17:30:43,784 [main] INFO  com.bwssystems.HABridge.BridgeSettings - Adding 192.168.20.24 as our default upnp config address.
2017-01-17 17:30:43,785 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2017-01-17 17:30:43,826 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2017-01-17 17:30:44.169:INFO::Thread-0: Logging initialized @1542ms
2017-01-17 17:30:44,296 [main] WARN  com.bwssystems.HABridge.dao.DeviceRepository - Error reading the file: data/device.db - Does not exist or is not readable. continuing...
2017-01-17 17:30:44,297 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
2017-01-17 17:30:44,346 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
2017-01-17 17:30:44,354 [main] INFO  com.bwssystems.util.UDPDatagramSender - Initializing UDP response Seocket...
2017-01-17 17:30:44,362 [main] INFO  com.bwssystems.util.UDPDatagramSender - UDP response Seocket initialized to: 50000
2017-01-17 17:30:44,463 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2017-01-17 17:30:44,470 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:80
2017-01-17 17:30:44.480:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2017-01-17 17:30:44,669 [Thread-0] ERROR spark.webserver.JettySparkServer - ignite failed
java.net.SocketException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:326)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:384)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at spark.webserver.JettySparkServer.ignite(JettySparkServer.java:131)
	at spark.SparkInstance.lambda$init$0(SparkInstance.java:341)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bwssytems** [comment]
This is your issue:

2017-01-17 17:30:44,470 [Thread-0] INFO spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:80
2017-01-17 17:30:44.480:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2017-01-17 17:30:44,669 [Thread-0] ERROR spark.webserver.JettySparkServer - ignite failed
java.net.SocketException: Permission denied

You need to allow access to port 80 on your system.

**Comment by narcosi** [comment]
Any idea how I do that?

Not sure why this would suddenly change after month of working perfectly ☹

Thanks for the awesome fast response

J

**Comment by bwssytems** [comment]
Have you installed software that now uses port 80? You will need to google your issues for your system. This is not an ha-bridge issue as it cannot get port 80 as something is preventing it, such as a new app using port 80.

**Comment by narcosi** [comment]
Not touched the pi since we installed HA

I don’t even know who to ask

Thanks for you help

J

**Comment by bwssytems** [comment]
Make sure the bridge is not running and then you can do a netstat -an and look for port 80 in the output. If it is not there, then you are not starting the ha-bridge with root privileges. As all things in the development area, try to learn the system. I say this as this is not commercial software and is hobbyist level knowledge.

**Comment by narcosi** [comment]
Sorry I was confused

It was ha bridge running which was causing the error

Please look at this log

It wont open the db file

I have a copy of it and its there – what can I do to get it back and working again?

Or is this still something I am doing wrong on the pi?

Thanks

Jon

2017-01-17 19:47:29,348 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.5.1) starting....
2017-01-17 19:47:29,390 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from system properties
2017-01-17 19:47:29,405 [main] INFO  com.bwssystems.HABridge.BridgeSettings - Adding 192.168.20.24 as our default upnp config address.
2017-01-17 19:47:29,407 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2017-01-17 19:47:29,448 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2017-01-17 19:47:29.772:INFO::Thread-0: Logging initialized @1502ms
2017-01-17 19:47:29,902 [main] WARN  com.bwssystems.HABridge.dao.DeviceRepository - Error reading the file: data/device.db - Does not exist or is not readable. continuing...
2017-01-17 19:47:29,902 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started....
2017-01-17 19:47:29,952 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
2017-01-17 19:47:29,961 [main] INFO  com.bwssystems.util.UDPDatagramSender - Initializing UDP response Seocket...
2017-01-17 19:47:29,969 [main] INFO  com.bwssystems.util.UDPDatagramSender - UDP response Seocket initialized to: 50000
2017-01-17 19:47:30,040 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2017-01-17 19:47:30,045 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:80
2017-01-17 19:47:30.056:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2017-01-17 19:47:30.208:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@80281d{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2017-01-17 19:47:30.211:INFO:oejs.Server:Thread-0: Started @1947ms
2017-01-17 19:47:30,844 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
2017-01-17 19:47:30,877 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
2017-01-17 19:47:30,880 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener running and ready....

**Comment by bwssytems** [comment]
It seems the default relative path data/device.db is not found as how you must be starting the bridge. It is all relative to which user starts the bridge and where it is started.

**Comment by narcosi** [comment]
So before it was starting ha in /etc/rc.local with the following line:

nohup java -jar /home/pi/habridge/ha-bridge-3.2.1.jar 2>&1 &

this I think was using a DB file in /data/

I have no idea what went wrong but thanks you’re your advice

I have moved it all into the home/pi directory and now I run: sudo /home/pi/habridge/starthabridge.sh from the rc.local

If you hadn’t explained  about user spaces this would have taken me forever

Thanks

Jon

**Comment by bwssytems** [comment]
When running on Linux based systems, the user will need to understand the user space and directory layouts. Also, if you are running on a pi, it is best to use this startup method that is listed first: https://github.com/bwssytems/ha-bridge#automation-on-linux-systems

**Comment by bwssytems** [comment]
Is this resolved?

**Comment by narcosi** [comment]
Yes thanks

______________________________

On 23 Jan 2017, at 15:16, BWS Systems <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this resolved?

-
