### ISSUE TITLE
Error connecting to Harmony Hub

### ISSUE THREAD

**Issue by DaRealDan** [bwssytems/ha-bridge#374]
I just installed ha-bridge 3.5.1 on Ubuntu 16.04, and configured my Harmony Hub with the correct IP address (checked the IP address twice in the Harmony Android App to make sure it's the right one) and saved and re-initialized ha-bridge.

But it won't show any Harmony actvities or devices. All I get from the log is this error message:

`01-21-2017 21:41:08.668	ERROR	Cannot get harmony client (Wohnzimmer) setup, Exiting with message: null	com.bwssystems.harmony.HarmonyHome`

I also tried rebooting my Ubuntu machine as well as the Harmony Hub (plug/unplug cable). I can ping the Hub from the Ubuntu machine and it shows up on my router network page. 

Any advice?

Thanks!

**Comment by crashandburn45** [comment]
I had the same issue. Luckily, the Echo supports harmony devices natively.

**Comment by DaRealDan** [comment]
Sadly this is not the case here in Germany - the Echo discovers the Harmony hub but due to a non existent Harmony skill it cannot be used.

**Comment by bwssytems** [comment]
@DaRealDan There was an exception that was written to the logfile, (it does not show up in the log tab) that we need to see. Please post the exception.

Thanks

**Comment by DaRealDan** [comment]
Here is the exception:

`2017-01-22 19:33:53.663:INFO:oejs.Server:Thread-40: Started @136258ms
2017-01-22 19:33:53,667 [main] ERROR com.bwssystems.harmony.HarmonyHome - Cannot                      get harmony client (Wohnzimmer) setup, Exiting with message: null
java.lang.NullPointerException: null
        at org.jivesoftware.smack.sasl.SASLMechanism.authenticate(SASLMechanism.                     java:170)
        at org.jivesoftware.smack.sasl.SASLMechanism.authenticate(SASLMechanism.                     java:148)
        at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentica                     tion.java:333)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.login(XMPPTCPConnection.                     java:244)
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:11                     6)
        at com.bwssystems.harmony.HarmonyServer.execute(HarmonyServer.java:78)
        at com.bwssystems.harmony.HarmonyServer.setup(HarmonyServer.java:50)
        at com.bwssystems.harmony.HarmonyHome.<init>(HarmonyHome.java:45)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:70)
Exception in thread "main" java.lang.NullPointerException
        at com.bwssystems.HABridge.dao.DeviceRepository._loadRepository(DeviceRe                     pository.java:63)
        at com.bwssystems.HABridge.dao.DeviceRepository.<init>(DeviceRepository.                     java:49)
        at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.<init>(Device                     Resource.java:50)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:80)

`

**Comment by bwssytems** [comment]
A question, did you build the ha-bridge yourself or did you use the downloaded jar?

**Comment by DaRealDan** [comment]
I used the jar provided for version 3.5.1 (wget https://github.com/bwssytems/ha-bridge/releases/download/v3.5.1/ha-bridge-3.5.1.jar)

**Comment by bwssytems** [comment]
You have your IP of your hub typed in properly in the bridge control tab? Also, take a look at your habridge.conf file to make sure it saved properly.

**Comment by DaRealDan** [comment]
Yep, I'm certain I entered the IP correctly (re-checked with Harmony android app Menu->Info->Version->Hub-IP-Address). It's also saved properly. Here is my current habridge.conf:

`{"upnpconfigaddress":"192.168.178.74","serverport":8080,"upnpresponseport":50000,"upnpdevicedb":"data/devices.db","harmonyaddress":{"devices":[{"name":"Wohnzimmer","ip":"192.168.178.54"}]},"buttonsleep":100,"upnpstrict":true,"traceupnp":false,"veraconfigured":false,"harmonyconfigured":true,"nestconfigured":false,"farenheit":false,"configfile":"data/habridge.config","numberoflogmessages":512,"hueconfigured":false,"halconfigured":false,"whitelist":{"WATuoP2eAz81HwpayUrG3WFnhOcItTpTgkoN403J":{"lastUseDate":"2017-01-22T19:52:35","createDate":"2017-01-22T19:52:35","name":"auto insert user"}},"settingsChanged":true,"myechourl":"alexa.amazon.de/spa/index.html#cards","webaddress":"192.168.178.74","mqttconfigured":false}`

**Comment by bwssytems** [comment]
So, lets try the beta for fun, look at #371

**Comment by bwssytems** [comment]
Let's get you upgraded to the new release instead of the beta:
https://github.com/bwssytems/ha-bridge/releases/download/v4.0.0/ha-bridge-4.0.0.jar

**Comment by DaRealDan** [comment]
Updated today, didn't help. Figured, there had to be something wrong with my network - so I unplugged the cable from the fritzbox that was connecting my linux server and plugged it back in a network switch. My network was setup like this: Internet -> Router #1 (this is where the Harmony hub is connected) -> Networkswitch -> Fritzbox 7240 -> Linux Server

Re-initialized the ha-bridge, and connecting to the Harmony Hub did work!

So now all I had to do was figure out what the hell is going on with the fritzbox... Until I figured it out:

For future references, disable "Transmit status information over UPnP" within your fritzbox (mine was a 7240, fritzos 6.06). You can disable it here: "Home Network" -> "Home Network Overview" -> "Network Settings" -> Untick "Transmit status information over UPnP" -> Apply to ave settings. I also unticked the option above UPnP, "Allow access for applications", saved and rebooted. After that the ha-bridge<-> Harmony Hub connection is still working with my linux server plugged into the fritzbox.

Thanks for your help and patience and keep up the good work!

**Comment by bwssytems** [comment]
Damn networks! always the hard one to figure out. Glad you got it resolved.
