### ISSUE TITLE
Cannot run Harmony Hub activities or control devices

### ISSUE THREAD

**Issue by DaRealDan** [bwssytems/ha-bridge#380]
After getting my Harmony Hub and ha-bridge (v. 4.0.0) to work together I encountered a new problem: Activities and device operations are simply not working. Nothing is happening.

Steps to reproduce on my system:

1. From the Harmony Activities tab I clicked "Build Item" to turn on / off my TV activity.

2. **The device that gets created has the following options:**
`Name: TV
Target: Wohnzimmer (name of Harmony Hub)
Device Type Activity
Map Type: Harmony Activity
Map ID: 5093105 
On items: Harmony Activity; Target Item: {"name":"5093105","hub":"Wohnzimmer"}
Off Items: Harmony Activity; Target Item: {"name":"-1","hub":"Wohnzimmer"}`

3. From the Bridge Devices tab in ha-bridge I click "Test ON" or "Test OFF" but nothing happens.

**The log shows the following error message:** 
`01-23-2017 20:47:22.938	ERROR		spark.webserver.MatcherFilter`

**After setting log level to DEBUG**
[...]
`01-23-2017 20:49:10.465	DEBUG	get splat	spark.Request
01-23-2017 20:49:10.465	DEBUG	hue state change requested: test from 192.168.178.72 body: {"on":false}	com.bwssystems.HABridge.hue.HueMulator
01-23-2017 20:49:10.466	DEBUG	Decode Json for url items: [{"item":"{\"name\":\"-1\",\"hub\":\"Wohnzimmer\"}","type":"harmonyActivity"}]	com.bwssystems.HABridge.hue.HueMulator
01-23-2017 20:49:10.466	DEBUG	executing HUE api request to change harmonyActivity to Harmony: Fire TV	com.bwssystems.HABridge.plugins.harmony.HarmonyHome
01-23-2017 20:49:10.467	ERROR		spark.webserver.MatcherFilter
01-23-2017 20:49:11.869	DEBUG	isSSDPDiscovery Found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
01-23-2017 20:49:11.870	DEBUG	isSSDPDiscovery Got SSDP packet from 192.168.178.61:47287, body: M-SEARCH * HTTP/1.1
 Host: 239.255.255.250:1900
 Content-Length: 0
 MAN: "ssdp:discover"
 MX: 2
 ST: urn:schemas-upnp-org:device:MediaServer:1
com.bwssystems.HABridge.upnp.UpnpListener
01-23-2017 20:49:13.003	DEBUG	httpMethod:get, uri: /system/logmsgs	spark.webserver.MatcherFilter
01-23-2017 20:49:13.004	DEBUG	get params	spark.Request
01-23-2017 20:49:13.004	DEBUG	get splat	spark.Request
01-23-2017 20:49:13.004	DEBUG	Get logmsgs.`

The ha-bridge log file shows the following errors:
`2017-01-23 20:50:55,047 [qtp360752523-14] ERROR spark.webserver.MatcherFilter -
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        at com.google.gson.Gson.fromJson(Gson.java:944)
        at com.google.gson.Gson.fromJson(Gson.java:917)
        at com.bwssystems.HABridge.plugins.harmony.HarmonyHome.deviceHandler(HarmonyHome.java:138)
        at com.bwssystems.HABridge.hue.HueMulator.changeState(HueMulator.java:793)
        at com.bwssystems.HABridge.hue.HueMulator.lambda$21(HueMulator.java:261)
        at spark.RouteImpl$1.handle(RouteImpl.java:58)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING
        at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:139)
        at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:70)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:209)
        ... 24 common frames omitted`

**Comment by bwssytems** [comment]
Yep, just found this myself for Harmony items.
