### ISSUE TITLE
MQTT - Test On/Off results in ERROR spark.webserver.MatcherFilter

### ISSUE THREAD

**Issue by szapalowski** [bwssytems/ha-bridge#392]
Edit: I realized that my comment filtered out some of my settings(specifically MQTT IP, User, and Pass) due to the formatting.  I've corrected the text below.

I've setup HA-Bridge on Windows 10(64bit) with jdk-8u121-windows-x64.  I've configured my MQTT server with the following properties:
Client ID: haBridge
IP: xxx.xxx.x.x:xxxx
User (opt): Mosquitto Username
Password (opt): Mosquitto Password

I then created an MQTT device using 'Build publish Message' and set the following propeties:

Name: haBridge/dev/test
Target: haBridge
Device Type (Informational):
Map Type (Legacy):
Unique Id (used for Hue responses): Given MAC
Map ID: haBridge/dev/test
On Items:
     Type: MQTT Message
     Target Item: {"clientId":"haBridge","topic":"/dev/test","message":" test message"}
     Delay:
     Count:
     Filter IPs:
     Http Verb:
     Http Body:
     Http Headers:
     Content Type:

Looking in the Google Home app on my phone, I'm able to see this device.  However trying to test On/Off from the HA-Bridge Device interface is resulting in "ERROR spark.webserver.MatcherFilter - com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 2 path" .  I've tried manipulating the Target Item JSON message but am still receiving errors.  Have I missed a config somewhere? Here is my log from startup to clicking the "On" button for the device:

`2017-01-25 00:41:13,263 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.0.2) starting....
2017-01-25 00:41:13,271 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
2017-01-25 00:41:13,310 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2017-01-25 00:41:13,316 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2017-01-25 00:41:13,354 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - Initializing UDP response Socket...
2017-01-25 00:41:13,356 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - UDP response Seocket initialized to: 50000
2017-01-25 00:41:13,359 [main] INFO  com.bwssystems.HABridge.plugins.harmony.HarmonyHome - Harmony Home created. No Harmony devices configured.
2017-01-25 00:41:13,360 [main] INFO  com.bwssystems.HABridge.plugins.NestBridge.NestHome - Nest Home created. No Nest configured.
2017-01-25 00:41:13,361 [main] INFO  com.bwssystems.HABridge.plugins.hue.HueHome - Hue passthru Home created. No Hue passtrhu systems configured.
2017-01-25 00:41:13,362 [main] INFO  com.bwssystems.HABridge.plugins.hal.HalHome - HAL Home created. No HAL devices configured.
2017-01-25 00:41:13,362 [main] INFO  com.bwssystems.HABridge.plugins.mqtt.MQTTHome - MQTT Home created.
2017-01-25 00:41:13,363 [main] INFO  com.bwssystems.HABridge.plugins.mqtt.MQTTHandler - Setting up handler for name: haBridge
2017-01-25 00:41:13.364:INFO::Thread-0: Logging initialized @269ms
2017-01-25 00:41:13,402 [main] INFO  com.bwssystems.HABridge.plugins.hass.HassHome - HomeAssistant Home created. No HomeAssistants configured.
2017-01-25 00:41:13,403 [main] INFO  com.bwssystems.HABridge.plugins.exec.CommandHome - Command Home for system program execution created.
2017-01-25 00:41:13,407 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2017-01-25 00:41:13,408 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:80
2017-01-25 00:41:13.409:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2017-01-25 00:41:13.446:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@18c447e{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2017-01-25 00:41:13.446:INFO:oejs.Server:Thread-0: Started @352ms
2017-01-25 00:41:13,546 [main] INFO  com.bwssystems.HABridge.plugins.http.HTTPHome - Http Home created.
2017-01-25 00:41:13,546 [main] INFO  com.bwssystems.HABridge.plugins.tcp.TCPHome - TCP Home created.
2017-01-25 00:41:13,547 [main] INFO  com.bwssystems.HABridge.plugins.udp.UDPHome - UDP Home created.
2017-01-25 00:41:13,547 [main] INFO  com.bwssystems.HABridge.plugins.vera.VeraHome - Vera Home created. No Veras configured.
2017-01-25 00:41:13,555 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started....
2017-01-25 00:41:13,561 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
2017-01-25 00:41:13,563 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
2017-01-25 00:41:13,576 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
2017-01-25 00:41:13,585 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener running and ready....
2017-01-25 00:41:37,103 [qtp23698074-18] ERROR spark.webserver.MatcherFilter -
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 2 path $
        at com.google.gson.Gson.fromJson(Gson.java:891)
        at com.google.gson.Gson.fromJson(Gson.java:844)
        at com.google.gson.Gson.fromJson(Gson.java:793)
        at com.google.gson.Gson.fromJson(Gson.java:765)
        at com.bwssystems.HABridge.plugins.mqtt.MQTTHome.deviceHandler(MQTTHome.java:91)
        at com.bwssystems.HABridge.hue.HueMulator.changeState(HueMulator.java:793)
        at com.bwssystems.HABridge.hue.HueMulator.lambda$21(HueMulator.java:261)
        at spark.RouteImpl$1.handle(RouteImpl.java:58)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        ... 24 common frames omitted`

**Comment by bwssytems** [comment]
Verified, new handling of json not working properly.
