### ISSUE TITLE
Home Assistant Discovery can't use SSL?

### ISSUE THREAD

**Issue by scottdalton** [bwssytems/ha-bridge#394]
It appears that the Home Assistant device discovery is http:// only and SSL fails to work?

**Comment by notoriousbdg** [comment]
Looks like I've hit this issue too.  The code does look to have http hardcoded.  Could you add optional support for https?

**Comment by jbardi** [comment]
Just curious, are these home assistant instances remote? If not, why not use the local ip address without SSL, unless there is a reason you would need SSL on a local network.

**Comment by scottdalton** [comment]
If you've set up home assistant directly with an SSL certificate, it only responds via SSL AFAIK.  There's no way to access it via IP directly.  

FWIW, I ended up just setting up a reverse proxy with SSL to local subdomains and getting rid of Home Assistant's built in use of certificates.  I'd run into a few other headaches like this which seemed to necessitate this. 

But if you're trying to use the tools Home Assistant provides, it will be a stumbling block, so it still seems like it may be a worthwhile feature for a lot of folks.

I look forward to using HA-Bridge now that I can get it talking directly to my HAss setup.  Appreciate the fast and good work on it!

**Comment by noodlemctwoodle** [comment]
Same issue as previously posted. I'm using my own wildcard SSL cert and I'm unable to access any Home Assistant entities with SSL enabled via Home Assistant config.

**Comment by notoriousbdg** [comment]
After upgrading to 4.1.0 and importimg the cert chain for my cert into the java keystone, I'm able to discover my home assistant devices.  Thanks @bwssytems. 

`sudo keytool -trustcacerts -keystore /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/security/cacerts -storepass changeit -noprompt -importcert -file /etc/letsencrypt/live/blah.com/chain.pem`

**Comment by anthonymcmenzie** [comment]
I am unclear as to whether this is meant to be fixed or not, however I am having the same issue.  I enable SSL on Home Assistant using a legitimate SSL certificate.  This certificate works without issue for any browser, the AWS skills, even iPhones !!!  When I enable an SSL HA Instance in HA Bridge, it fails with the following error(s).  I've tried a few workarounds (temporarily disabling SSL, setting up an HASS device in HA Bridge, discovering - works fine - and setting up a "switch" - also works fine - then leaving the switch in situ, deleting and recreating the HASS device (back with SSL) in the bridge config, restart etc.  Still fails, though I think it's trying to use SSL as the messages below show.  I am happy to be a tester of this

For what it's worth (and apologies, I'm no expert on any of this), I think the SSL call is going out okay but it's something to do with not being able to validate the authenticity of the certificate.  As it's a legitimate (not self certified) version, this is something I wouldn't have expected to happen.

2017-02-25 07:12:03,596 [qtp19327982-17] WARN  com.bwssystems.HABridge.plugins.http.HTTPHandler - Error calling out to HA gateway: IOException in log
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.bwssystems.HABridge.plugins.http.HTTPHandler.doHttpRequest(HTTPHandler.java:109)
        at com.bwssystems.HABridge.plugins.hass.HomeAssistant.callCommand(HomeAssistant.java:65)
        at com.bwssystems.HABridge.plugins.hass.HassHome.deviceHandler(HassHome.java:144)
        at com.bwssystems.HABridge.hue.HueMulator.changeState(HueMulator.java:979)
        at com.bwssystems.HABridge.hue.HueMulator.lambda$35(HueMulator.java:392)
        at spark.RouteImpl$1.handle(RouteImpl.java:58)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 44 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
        at java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 50 common frames omitted
