### ISSUE TITLE
Harmony Button Issue. Expected BEGIN_ARRAY but was STRING at line 1 column 2 

### ISSUE THREAD

**Issue by shizeon** [bwssytems/ha-bridge#398]
Having fun playing with this software! I setup some Harmony Activities and they work great. However, when I try to add a Harmony Button I get the following error when attempt to test it through the HA Bridges website..

I'm using ha-bridge-4.0.2.jar

```
2017-01-25 09:03:02,328 [main] DEBUG com.bwssystems.HABridge.upnp.UpnpListener - Sending notify packet for upnp.
2017-01-25 09:03:03,916 [qtp1042874215-17] DEBUG spark.webserver.MatcherFilter - httpMethod:get, uri: /api/0a4d9dccdf2649e39c3f1b09e644e318/lights
2017-01-25 09:03:03,917 [qtp1042874215-17] DEBUG spark.Request - get params
2017-01-25 09:03:03,917 [qtp1042874215-17] DEBUG spark.Request - matchedPart: :userid = 0a4d9dccdf2649e39c3f1b09e644e318
2017-01-25 09:03:03,917 [qtp1042874215-17] DEBUG spark.Request - get splat
2017-01-25 09:03:03,917 [qtp1042874215-17] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue lights list requested: 0a4d9dccdf2649e39c3f1b09e644e318 from 192.168.128.229
2017-01-25 09:03:04,511 [qtp1042874215-14] DEBUG spark.webserver.MatcherFilter - httpMethod:put, uri: /api/test/lights/5/state
2017-01-25 09:03:04,512 [qtp1042874215-14] DEBUG spark.Request - get params
2017-01-25 09:03:04,512 [qtp1042874215-14] DEBUG spark.Request - matchedPart: :userid = test
2017-01-25 09:03:04,512 [qtp1042874215-14] DEBUG spark.Request - matchedPart: :id = 5
2017-01-25 09:03:04,512 [qtp1042874215-14] DEBUG spark.Request - get splat
2017-01-25 09:03:04,549 [qtp1042874215-14] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue state change requested: test from 192.168.128.210 body: {"on":true}
2017-01-25 09:03:04,551 [qtp1042874215-14] DEBUG com.bwssystems.HABridge.hue.HueMulator - Decode Json for url items: [{"item":"{\"device\":\"26836783\",\"button\":\"PowerOn\",\"hub\":\"Front Room Harmony\"}","type":"harmonyButton","delay":"100","count":"1"}]
2017-01-25 09:03:04,563 [qtp1042874215-14] DEBUG com.bwssystems.HABridge.plugins.harmony.HarmonyHome - executing HUE api request to change harmonyButton to Harmony: TV
2017-01-25 09:03:04,588 [qtp1042874215-14] ERROR spark.webserver.MatcherFilter -
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 2 path $
        at com.google.gson.Gson.fromJson(Gson.java:891)
        at com.google.gson.Gson.fromJson(Gson.java:844)
        at com.google.gson.Gson.fromJson(Gson.java:793)
        at com.google.gson.Gson.fromJson(Gson.java:765)
        at com.bwssystems.HABridge.plugins.harmony.HarmonyHome.deviceHandler(HarmonyHome.java:159)
        at com.bwssystems.HABridge.hue.HueMulator.changeState(HueMulator.java:793)
        at com.bwssystems.HABridge.hue.HueMulator.lambda$21(HueMulator.java:261)
        at spark.RouteImpl$1.handle(RouteImpl.java:58)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        ... 24 common frames omitted
2017-01-25 09:03:06,095 [qtp1042874215-12] DEBUG spark.webserver.MatcherFilter - httpMethod:get, uri: /api/c82c3e375ae74994af6e4928427002a0/lights
2017-01-25 09:03:06,095 [qtp1042874215-12] DEBUG spark.Request - get params
2017-01-25 09:03:06,095 [qtp1042874215-12] DEBUG spark.Request - matchedPart: :userid = c82c3e375ae74994af6e4928427002a0
2017-01-25 09:03:06,095 [qtp1042874215-12] DEBUG spark.Request - get splat
2017-01-25 09:03:06,096 [qtp1042874215-12] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue lights list requested: c82c3e375ae74994af6e4928427002a0 from 192.168.128.247
2017-01-25 09:03:08,378 [main] DEBUG com.bwssystems.HABridge.upnp.UpnpListener - isSSDPDiscovery Found message to be an M-SEARCH message.
2017-01-25 09:03:08,379 [main] DEBUG com.bwssystems.HABridge.upnp.UpnpListener - isSSDPDiscovery Got SSDP packet from 192.168.128.253:34787, body: M-SEARCH * HTTP/1.1^M
Host: 239.255.255.250:1900^M
Man: "ssdp:discover"^M
ST: ssdp:all^M
MX: 5^M
```

The button ON is setup as {"device":"26836783","button":"PowerOn","hub":"Front Room Harmony"}. I've tried it with delay, count set and not set and same results.

Any idea what's up?

Thanks!

**Comment by bwssytems** [comment]
Verified. Json handling issue.

**Comment by shizeon** [comment]
Working perfectly in 4.0.3. Thank you!
