### ISSUE TITLE
Harmony control

### ISSUE THREAD

**Issue by emiliosic** [bwssytems/ha-bridge#4]
Tried to set up harmony control on release 1.0.6 (built from Maven), but fails to start. It works if I don't provode the harmony parameters:

/usr/bin/java -jar -Dvera.address=192.168.150.11 -Dupnp.device.db=/opt/ha-bridge/data/device.db -Dharmony.address=192.168.150.23 -Dharmony.user=<removed>\@<removed> -Dharmony.pwd=<password> -Dtrace.upnp=false /opt/ha-bridge/server/ha-bridge-1.0.6.jar
[main] INFO com.bwssystems.HABridge.HABridge - HA Bridge (v1.0.6) starting setup....
Nov 04, 2015 12:06:43 AM org.jivesoftware.smack.provider.ProviderFileLoader <init>
SEVERE: Unknown error occurred while parsing provider file
org.xmlpull.v1.XmlPullParserException: caused by: org.xmlpull.v1.XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:294)
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:259)
	at org.jivesoftware.smack.provider.ProviderFileLoader.<init>(ProviderFileLoader.java:59)
	at org.jivesoftware.smack.provider.ProviderFileLoader.<init>(ProviderFileLoader.java:49)
	at net.whistlingfish.harmony.HarmonyClientModule.configure(HarmonyClientModule.java:16)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:259)
	at com.google.inject.spi.Elements.getElements(Elements.java:109)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.bwssystems.harmony.HarmonyServer.setup(HarmonyServer.java:39)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:79)

[main] INFO com.bwssystems.harmony.HarmonyServer - setup initiated ....
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.jivesoftware.smack.ConnectionConfiguration.<init>(ConnectionConfiguration.java:67)
	at net.whistlingfish.harmony.HarmonyClient.createConnectionConfig(HarmonyClient.java:311)
	at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:113)
	at com.bwssystems.harmony.HarmonyServer.execute(HarmonyServer.java:68)
	at com.bwssystems.harmony.HarmonyServer.setup(HarmonyServer.java:43)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:79)
Caused by: java.lang.IllegalStateException: org.xmlpull.v1.XmlPullParserException: caused by: org.xmlpull.v1.XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available
	at org.jivesoftware.smack.SmackConfiguration.<clinit>(SmackConfiguration.java:158)
	... 6 more
Caused by: org.xmlpull.v1.XmlPullParserException: caused by: org.xmlpull.v1.XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:294)
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:259)
	at org.jivesoftware.smack.SmackConfiguration.processConfigFile(SmackConfiguration.java:352)
	at org.jivesoftware.smack.SmackConfiguration.processConfigFile(SmackConfiguration.java:347)
	at org.jivesoftware.smack.SmackConfiguration.<clinit>(SmackConfiguration.java:155)
	... 6 more

**Comment by bwssytems** [comment]
Fixed in new release of v1.0.7
