### ISSUE TITLE
UpnpListener encountered an error opening sockets. Shutting down java.net.SocketException: Invalid argument

### ISSUE THREAD

**Issue by MyGreenBodhi** [bwssytems/ha-bridge#41]
i've tried to migrate for a standalone RPi to running the bridge in a Freenas Jail.

The webserver runs without issue and I can add devices..the UpnpListener does not run due to an error.
Any thoughts on what I can try to debug this?

Here is the log file

> [main] INFO com.bwssystems.HABridge.HABridge - HA Bridge (v1.3.7) starting setup....
[main] INFO com.bwssystems.NestBridge.NestHome - not a valid nest
[main] DEBUG com.bwssystems.HABridge.dao.DeviceRepository - Read a Device - device json id: 1373210256
[main] DEBUG com.bwssystems.HABridge.dao.DeviceRepository - Read a Device - device json name: Foyer
[main] DEBUG com.bwssystems.HABridge.dao.DeviceRepository - Read a Device - device json name: 63
[main] DEBUG com.bwssystems.HABridge.dao.DeviceRepository - Read a Device - device json name: veraDevice
[main] DEBUG com.bwssystems.HABridge.dao.DeviceRepository - Read a Device - device json type:switch
[main] DEBUG com.bwssystems.HABridge.dao.DeviceRepository - Read a Device - device json type:Encapsulated
[main] DEBUG com.bwssystems.HABridge.dao.DeviceRepository - Read a Device - device json off URL:http://192.168.1.88:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=63
[main] DEBUG com.bwssystems.HABridge.dao.DeviceRepository - Read a Device - device json on URL:http://192.168.1.88:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=63
[main] INFO com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
[main] DEBUG spark.route.RouteMatcherFactory - creates RouteMatcher
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: options, /api/devices, spark.RouteImpl$1@c038203
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: post, /api/devices, spark.ResponseTransformerRouteImpl$1@4b9e13df
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: options, /api/devices/:id, spark.RouteImpl$1@475530b9
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: put, /api/devices/:id, spark.ResponseTransformerRouteImpl$1@26be92ad
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/devices, spark.ResponseTransformerRouteImpl$1@224edc67
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/devices/:id, spark.ResponseTransformerRouteImpl$1@46d56d67
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: delete, /api/devices/:id, spark.ResponseTransformerRouteImpl$1@59fa1d9b
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/devices/habridge/version, spark.RouteImpl$1@4501b7af
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/devices/vera/devices, spark.ResponseTransformerRouteImpl$1@5b275dab
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/devices/vera/scenes, spark.ResponseTransformerRouteImpl$1@29774679
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/devices/harmony/activities, spark.ResponseTransformerRouteImpl$1@5e5792a0
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/devices/harmony/show, spark.ResponseTransformerRouteImpl$1@3532ec19
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/devices/harmony/devices, spark.ResponseTransformerRouteImpl$1@ae45eb6
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/devices/nest/items, spark.ResponseTransformerRouteImpl$1@27efef64
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/devices/backup/available, spark.ResponseTransformerRouteImpl$1@47c62251
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: options, /api/devices/backup/create, spark.RouteImpl$1@66a3ffec
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: put, /api/devices/backup/create, spark.ResponseTransformerRouteImpl$1@1e88b3c
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: options, /api/devices/backup/delete, spark.RouteImpl$1@3bfdc050
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: post, /api/devices/backup/delete, spark.ResponseTransformerRouteImpl$1@5e3a8624
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: options, /api/devices/backup/restore, spark.RouteImpl$1@91161c7
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: post, /api/devices/backup/restore, spark.ResponseTransformerRouteImpl$1@6a4f787b
2016-02-06 12:06:52.967:INFO::Thread-0: Logging initialized @1915ms
[Thread-0] INFO spark.webserver.JettySparkServer - == Spark has ignited ...
[Thread-0] INFO spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:8080
2016-02-06 12:06:53.230:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2016-02-06 12:06:53.375:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@5cd48b31{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-02-06 12:06:53.377:INFO:oejs.Server:Thread-0: Started @2325ms
[main] INFO com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/:userid/lights, spark.ResponseTransformerRouteImpl$1@133e16fd
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: options, /api, spark.RouteImpl$1@1ad282e0
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: post, /api, spark.RouteImpl$1@1cab0bfb
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: options, /api/*, spark.RouteImpl$1@50de0926
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: post, /api/*, spark.RouteImpl$1@60438a68
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/config, spark.ResponseTransformerRouteImpl$1@3439f68d
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/:userid/config, spark.ResponseTransformerRouteImpl$1@71d15f18
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/:userid, spark.ResponseTransformerRouteImpl$1@6c9f5c0d
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /api/:userid/lights/:id, spark.ResponseTransformerRouteImpl$1@76b10754
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: options, /api/:userid/lights/:id/state, spark.RouteImpl$1@3d8314f0
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: put, /api/:userid/lights/:id/state, spark.RouteImpl$1@530612ba
[main] INFO com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /description.xml, spark.RouteImpl$1@74294adb
[main] DEBUG spark.route.SimpleRouteMatcher - Adds route: get, /upnp/settings, spark.ResponseTransformerRouteImpl$1@130f889
[main] INFO com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
[main] INFO com.bwssystems.HABridge.upnp.UpnpListener - Traceupnp: epair0b ... has addr /192.168.1.50
[main] DEBUG com.bwssystems.HABridge.upnp.UpnpListener - Checking epair0b to our interface set
[main] ERROR com.bwssystems.HABridge.upnp.UpnpListener - UpnpListener encountered an error opening sockets. Shutting down
java.net.SocketException: Invalid argument
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.joinGroup(AbstractPlainDatagramSocketImpl.java:203)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:406)
	at com.bwssystems.HABridge.upnp.UpnpListener.startListening(UpnpListener.java:65)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:150)
[main] INFO com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener Stopped

**Comment by MyGreenBodhi** [comment]
my mistake, i forgot -Djava.net.preferIPv4Stack=true
