### ISSUE TITLE
Error thrown when retrieving Domoticz devices (ha-bridge 4.1.0/Domoticz beta 3.6518)

### ISSUE THREAD

**Issue by jeroenvanpelt** [bwssytems/ha-bridge#414]
Running ha-bridge 4.1.0 on a Raspberry Pi (Raspbian Wheezy) together with Domoticz V3.6518 (beta) and JRE 1.8.0-b132.

I added Domoticz to the config: 10.0.1.242, port 8080 (no user/pwd) so that I can automatically retrieve all devices from it. After saving the config ha-bridge logs an error though and no devices are shown. I have added devices manually pointing to the same Domoticz config that do work. 

Here's the error from the log:

2017-01-28 07:18:44,784 [main] INFO  spark.webserver.JettySparkServer - >>> Spark shutting down ...
...skipping...
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        at com.google.gson.Gson.fromJson(Gson.java:844)
        at com.google.gson.Gson.fromJson(Gson.java:793)
        at com.google.gson.Gson.fromJson(Gson.java:765)
        at com.bwssystems.HABridge.plugins.domoticz.DomoticzHandler.getDomoticzDevices(DomoticzHandler.java:47)
        at com.bwssystems.HABridge.plugins.domoticz.DomoticzHandler.getDevices(DomoticzHandler.java:30)
        at com.bwssystems.HABridge.plugins.domoticz.DomoticzHome.getItems(DomoticzHome.java:39)
        at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.lambda$17(DeviceResource.java:219)
        at com.bwssystems.HABridge.devicemanagmeent.DeviceResource$$Lambda$39/8391338.handle(Unknown Source)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NumberFormatException: Expected an int but was 18.268000000000001 at line 2927 column 42 path $.result[66].AddjValue
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1202)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:247)
        ... 35 common frames omitted

**Comment by bwssytems** [comment]
So, it seems something in the return is not handled by the parser for the domoticz devices. Will need more info. Can you turn on debug for com.bwssystems.HABridge.plugins.domoticz and post output. Thanks

**Comment by jeroenvanpelt** [comment]
Enabled debugging for the Domoticz related modules and was able to determine that the problem is in the device output below.

This is MySensors water sensor, for which I have entered a meter off-set of 18.268. After changing that to 18,268, ha-bridge was able to retrieve all devices from Domoticz succesfully. (In the Domoticz interface the meter off-set changed to "18", which sounds something ha-bridge expects). Starting to doubt now, whether this might be an issue with Domoticz, rather than ha-bridge perse.  

      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 18.268000000000001,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "18.348 m3",
         "CounterToday" : "0",
         "CustomImage" : 0,
         "Data" : "18.348 m3",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 21,
         "HardwareName" : "MySensors GW LocalSerial",
         "HardwareType" : "MySensors Gateway USB",
         "HardwareTypeVal" : 41,
         "HaveTimeout" : true,
         "ID" : "0501",
         "LastUpdate" : "2017-01-21 13:10:20",
         "Name" : "Water",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "RFXMeter counter",
         "SwitchTypeVal" : 2,
         "Timers" : "false",
         "Type" : "RFXMeter",
         "TypeImg" : "counter",
         "Unit" : 0,
         "Used" : 1,
         "ValueQuantity" : "",
         "ValueUnits" : "",
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "370"
      },

**Comment by ayounas** [comment]
Hello
I have  similar issue due to a negative value in one of my domoticz device


```
2017-01-29 21:02:49,032 [qtp13053708-29] ERROR spark.webserver.MatcherFilter - 
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was -40.299999999999997 at line 1419 column 43 path $.result[30].AddjValue
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        at com.google.gson.Gson.fromJson(Gson.java:844)
        at com.google.gson.Gson.fromJson(Gson.java:793)
        at com.google.gson.Gson.fromJson(Gson.java:765)
        at com.bwssystems.HABridge.plugins.domoticz.DomoticzHandler.getDomoticzDevices(DomoticzHandler.java:47)
        at com.bwssystems.HABridge.plugins.domoticz.DomoticzHandler.getDevices(DomoticzHandler.java:30)
        at com.bwssystems.HABridge.plugins.domoticz.DomoticzHome.getItems(DomoticzHome.java:39)
        at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.lambda$17(DeviceResource.java:219)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: Expected an int but was -40.299999999999997 at line 1419 column 43 path $.result[30].AddjValue
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1202)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:247)
        ... 34 common frames omitted


```
Debug output for the device showing AddjValue is negative which is causing problem. 
```
 {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : -40.299999999999997,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "4.1 C, 90 %",
         "Description" : "",
         "DewPoint" : "2.61",
         "Favorite" : 0,
         "HardwareID" : 7,
         "HardwareName" : "RFLink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveTimeout" : false,
         "Humidity" : 90,
         "HumidityStatus" : "Wet",
         "ID" : "0093",
         "LastUpdate" : "2017-01-29 21:02:18",
         "Name" : "Outside Temperature",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WTGR800",
         "Temp" : 4.0999999999999996,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "157"
      },
```

**Comment by ayounas** [comment]
Hello Again

So changing value from -40.3 in domoticz to just -40 without decimal seems to fix the issue, so its not due to negative value but could be the number of digits after decimal. Not entirely sure why domoticz is converting one value after decimal to many.

```
 {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : -40.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "4.4 C, 90 %",
         "Description" : "",
         "DewPoint" : "2.90",
         "Favorite" : 0,
         "HardwareID" : 7,
         "HardwareName" : "RFLink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveTimeout" : false,
         "Humidity" : 90,
         "HumidityStatus" : "Wet",
         "ID" : "0093",
         "LastUpdate" : "2017-01-29 21:16:43",
         "Name" : "Outside Temperature",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WTGR800",
         "Temp" : 4.4000000000000004,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "157"
      },
```

**Comment by bwssytems** [comment]
This is new, so seeing more configurations will help. Will look into this more

**Comment by ayounas** [comment]
Hello 
do you need full debug out from logs or need some specific configuration ?.

Thanks

**Comment by bwssytems** [comment]
A lot of good JSON constructs to work with here, I'll start with that. Will let you know if I need more.

**Comment by bwssytems** [comment]
So it looks like when I used the JSON generator I didn't let it select Double instead of Integer.

**Comment by bwssytems** [comment]
Since I only need a few fields, I have changed the what needs to be decoded.
