### ISSUE TITLE
issue with passing variables in - not accepted ? ip port or listener ?

### ISSUE THREAD

**Issue by willplaice** [bwssytems/ha-bridge#45]
### ns:target administrator$ java -jar ha-bridge-1.3.8.jar -Dupnp.config.address=192.168.1.243 -Dserver.port=8081 -Dupnp.response.port=50099
[main] INFO com.bwssystems.HABridge.HABridge - HA Bridge (v1.3.8) starting setup....
[main] INFO com.bwssystems.HABridge.HABridge - Getting an IP address for this host....
[main] INFO com.bwssystems.HABridge.HABridge - Adding 192.168.1.243 from interface ppp0 as our default upnp config address.
[main] INFO com.bwssystems.NestBridge.NestHome - not a valid nest
[main] INFO com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
2016-02-09 13:33:14.276:INFO::Thread-0: Logging initialized @3509ms
[Thread-0] INFO spark.webserver.JettySparkServer - == Spark has ignited ...
[Thread-0] INFO spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:8080
2016-02-09 13:33:14.779:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2016-02-09 13:33:15.094:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@7e762fc5{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-02-09 13:33:15.095:INFO:oejs.Server:Thread-0: Started @4410ms
[main] INFO com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
[main] INFO com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
[main] INFO com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
[main] ERROR com.bwssystems.HABridge.upnp.UpnpListener - UpnpListener encountered an error opening sockets. Shutting down

**Comment by bwssytems** [comment]
It needs to be in a specific order for Java command lines. Parameters go before the jar like this: 

java -jar -Dupnp.config.address=192.168.1.243 -Dserver.port=8081 -Dupnp.response.port=50099  ha-bridge-1.3.8.jar

**Comment by willplaice** [comment]
ok changed and it picked up the port ok - but i think i'm still stuck on the udp settings ?


ns:target administrator$ java -jar -Dupnp.config.address=192.168.1.243 -Dserver.port=8081 -Dupnp.response.port=50005 ha-bridge-1.3.8.jar
[main] INFO com.bwssystems.HABridge.HABridge - HA Bridge (v1.3.8) starting setup....
[main] INFO com.bwssystems.NestBridge.NestHome - not a valid nest
[main] INFO com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
2016-02-09 14:51:31.743:INFO::Thread-0: Logging initialized @257ms
[Thread-0] INFO spark.webserver.JettySparkServer - == Spark has ignited ...
[Thread-0] INFO spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:8081
2016-02-09 14:51:31.812:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2016-02-09 14:51:31.848:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@41bdaf97{HTTP/1.1,[http/1.1]}{0.0.0.0:8081}
2016-02-09 14:51:31.848:INFO:oejs.Server:Thread-0: Started @365ms
[main] INFO com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
[main] INFO com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
[main] INFO com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
[main] ERROR com.bwssystems.HABridge.upnp.UpnpListener - UpnpListener encountered an error opening sockets. Shutting down
java.net.SocketException: Address already in use
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.joinGroup(AbstractPlainDatagramSocketImpl.java:203)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:406)
	at com.bwssystems.HABridge.upnp.UpnpListener.startListening(UpnpListener.java:65)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:150)
[main] INFO com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener Stopped

**Comment by bwssytems** [comment]
You have a process already running using that port identified by the error "java.net.SocketException: Address already in use" above. 

Make sure you did not leave any java processes running.

**Comment by willplaice** [comment]
ok (and thanks very much for helping)

i don't see another java service (ps -e shows nothing) and I see nothing listening on any UDP port:

ns:~ administrator$ lsof -Pi | grep LISTEN
iTunes      820 administrator   24u  IPv4 0xd11b959432f0e0fb      0t0  TCP *:54749 (LISTEN)
iTunes      820 administrator   36u  IPv4 0xd11b959432f7f0fb      0t0  TCP *:3689 (LISTEN)
iTunes      820 administrator   37u  IPv6 0xd11b9594320f449b      0t0  TCP *:3689 (LISTEN)
Plex\x20M  1024 administrator   59u  IPv4 0xd11b959432eff8e3      0t0  TCP *:32400 (LISTEN)
Plex\x20M  1024 administrator   60u  IPv4 0xd11b9594346460fb      0t0  TCP *:32401 (LISTEN)
Plex\x20S  1083 administrator   10u  IPv4 0xd11b9594368258e3      0t0  TCP *:58103 (LISTEN)
Plex\x20S  1399 administrator    4u  IPv4 0xd11b959432f488e3      0t0  TCP *:64124 (LISTEN)
java      74048 administrator   27u  IPv6 0xd11b95943920bf5b      0t0  TCP *:8081 (LISTEN)


(running on OSX).... would appreciate any other advice ?

**Comment by bwssytems** [comment]
So looking at this a bit more, it seems that OSX is not letting you join the multicast port for upnp! Not good. This is the default port (1900) for listening to the broadcast requests for upnp config and is supposed to be joinable. Wondering if iti is a permissions issue. Not an OSX person, but is there a "root" level user that can be tried as it may be a permissions issue.

**Comment by willplaice** [comment]
ok let me put this into a Debian VM and retry

**Comment by cr4zyg047** [comment]
Here's a BAT file example that gives you an easily customizable example. Configure the parameters like IP - but port is optional.

A friend wrote this yesterday to make running it easier for himself.

https://github.com/dale3h/amazon-echo-bridge-launcher

**Comment by bwssytems** [comment]
No activity so closing this issue.

**Comment by willplaice** [comment]
Just wanted to say thanks. All working on Ubuntu 

Will
