### ISSUE TITLE
Running habridge on osmc - Null Pointer Exception when no habridge.conf

### ISSUE THREAD

**Issue by bradds** [bwssytems/ha-bridge#558]
Hi.

I am trying to install habridge on osmc but am unable to get it running.
I have successfully installed and run it on raspbian but I keep getting these errors in the log on osmc
I have installed the latest JDK 1.8 
Any help would be appreciated.

2017-03-18 02:25:08,727 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.3.0) starting....
2017-03-18 02:25:08,774 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /home/osmc/habridge/data/habridge.config
2017-03-18 02:25:09,280 [main] WARN  com.bwssystems.HABridge.BridgeSettings - Issue loading values from file: file:///home/osmc/habridge/data/habridge.config, Gson convert failed.
2017-03-18 02:25:09,304 [main] INFO  com.bwssystems.HABridge.BridgeSettings - Adding 192.168.1.10 as our default upnp config address.
Exception in thread "main" java.lang.NullPointerException
        at com.bwssystems.HABridge.BridgeSettingsDescriptor.setupInternalTestUser(BridgeSettingsDescriptor.java:438)
        at com.bwssystems.HABridge.BridgeSettings.setupInternalTestUser(BridgeSettings.java:314)
        at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:177)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:49)

**Comment by Twit123** [comment]
Hi Bradds,

I don't think it's your osmc, I see you tried to run 4.3.0, I run on Ubuntu and 4.3.0 fails to start with the same error. 4.2.1 runs with no issues here.

/opt/habridge# java -jar -Dserver.port=8090 ha-bridge-4.3.0.jar
2017-03-18 06:46:50,611 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.3.0) starting....
2017-03-18 06:46:50,621 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
Exception in thread "main" java.lang.NullPointerException
        at com.bwssystems.HABridge.BridgeSettingsDescriptor.setupInternalTestUser(BridgeSettingsDescriptor.java:438)
        at com.bwssystems.HABridge.BridgeSettings.setupInternalTestUser(BridgeSettings.java:314)
        at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:177)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:49)

**Comment by bradds** [comment]
Thanks Twit123

I have managed to get 4.3.0 running by manually editing the habridge.config file to show osmc path and ip address. (taken from a working habridge.config file on raspian).

Note for anyone else trying this, you have to manually create the /home/osmc/data directory and put in your own habridge.config file for this to work.

**Comment by bwssytems** [comment]
This is a bug for the startup when no habridge.conf exists
