### ISSUE TITLE
HA Bridge Exits/Crashes after random time

### ISSUE THREAD

**Issue by zappalag** [bwssytems/ha-bridge#633]
Hi, I've been using HA Bridge for quite some time with no issues.  A couple of days ago, it started to crash after random times.  Sometimes it crashes after 3 or 4 minutes, sometimes after a few hours... I'm hoping you can point me in the right direction.  

Here's a copy of the last start/crash from my system: 

sudo java -jar -Dvera.address=192.168.1.250 -Dupnp.config.address=192.168.1.111 -Dserver.port=9090 ha-bridge-3.2.0.jar
Password:
2017-05-15 21:47:43,345 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.2.0) starting....
2017-05-15 21:47:43,354 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
2017-05-15 21:47:43,397 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.2.0) initializing....
2017-05-15 21:47:43,404 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2017-05-15 21:47:43.461:INFO::Thread-0: Logging initialized @527ms
2017-05-15 21:47:43,504 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2017-05-15 21:47:43,506 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:9090
2017-05-15 21:47:43.509:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2017-05-15 21:47:43.543:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@5f29a123{HTTP/1.1,[http/1.1]}{0.0.0.0:9090}
2017-05-15 21:47:43.543:INFO:oejs.Server:Thread-0: Started @610ms
2017-05-15 21:47:43,675 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
2017-05-15 21:47:43,682 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
2017-05-15 21:47:43,684 [main] INFO  com.bwssystems.util.UDPDatagramSender - Initializing UDP response Seocket...
2017-05-15 21:47:43,685 [main] INFO  com.bwssystems.util.UDPDatagramSender - UDP response Seocket initialized to: 50000
2017-05-15 21:47:43,693 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
2017-05-15 21:47:43,699 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
2017-05-15 21:47:43,701 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener running and ready....
2017-05-16 07:37:35,782 [main] ERROR com.bwssystems.HABridge.upnp.UpnpListener - UpnpListener encountered an error sending upnp response packet. Shutting down
java.io.IOException: No route to host (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at com.bwssystems.util.UDPDatagramSender.sendUDPResponse(UDPDatagramSender.java:70)
	at com.bwssystems.HABridge.upnp.UpnpListener.sendUpnpResponse(UpnpListener.java:215)
	at com.bwssystems.HABridge.upnp.UpnpListener.startListening(UpnpListener.java:127)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:94)
2017-05-16 07:37:36,788 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener - ended, error found
2017-05-16 07:37:36,821 [main] INFO  spark.webserver.JettySparkServer - >>> Spark shutting down ...
2017-05-16 07:37:36.828:INFO:oejs.ServerConnector:main: Stopped ServerConnector@5f29a123{HTTP/1.1,[http/1.1]}{0.0.0.0:9090}
2017-05-16 07:37:36,846 [main] INFO  spark.webserver.JettySparkServer - done
2017-05-16 07:37:36,846 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.2.0) exiting....

To note, there was a configuration change on my home network a few days back.  A new service provider installed a new router (ATT/Uverse), but we configured it on its own IP (172.16.x.x) and DMZ to my existing router (ASUS).  The ASUS and all connected devices to it maintained the same 192.168.x.x IP's and same DHCP Reservations.  In my mind, my internal network is 'the same as before', but it's odd that HABridge is now crashing...  Any help would be greatly appreciated!!  Thank you in advance!!!

**Comment by bwssytems** [comment]
are you using wifi and dhcp?

**Comment by zappalag** [comment]
HABridge is (and has been) running on an iMac hard-wired to my ASUS router using a reserved DHCP IP.

It was running with no issues apparently until the new ATT router was installed and added to my network.

For clarification, the ATT router sits in front of my ASUS to bring in TV and Internet over fiber.  It has a 172.16.x.x Network address, its Wi-Fi disabled and DMZ open to the ASUS router.  The ASUS is on a 192.168.x.x network (same it's always been) with a DHCP table reservation to assign IP's to various devices such as my iMac, my home automation hub (Vera plus), Philips Hue hub, Lutron Hub, etc.  All these devices are hard-wired to the ASUS via a switch.  This configuration was exactly the same as before for all devices connected to the ASUS.  The difference is that the ASUS was connected to a cable modem before instead of the ATT router.

Thanks for looking into this!
G

**Comment by bwssytems** [comment]
So the new router is doing something as your error "No route to host (sendto failed)" identifies that the iMac cannot send a UDP message back.

**Comment by bwssytems** [comment]
Maybe I'll make that less stringent on this error if it is transient.

**Comment by zappalag** [comment]
Thanks again...

Should I wait for some kind of update from you?

**Comment by bwssytems** [comment]
No, as you are still having some type of network issue. This enhancement will make it so it does not shutdown on this issue as it may be transient. I would check that your new router handles UDP datagram sending properly.

**Comment by zappalag** [comment]
Hi, I updated to the latest version of HABridge (4.1.4) and it appears to be working…  the console logging is a bit more verbose and the UDP Warning (instead of a shutdown) is great.  I configured my Harmony Hubs and I still get some UDP warnings.  The service does not shut down, but I see a few java exception errors.

I am attaching an excerpt of my latest log hoping you can take a look and let me know if all these errors/warnings are OK or if you can help me identify why I keep getting them.  The offender IP’s are reserved for Harmony Hubs.  I have three of these hubs, but not all generate the errors.

Thanks again for the great support!

**Comment by bwssytems** [comment]
The latest release is actually 4.5.0. Where are you going to get your releases?

**Comment by zappalag** [comment]
I went here:

**Comment by bwssytems** [comment]
Well your best bet is this github site for the ha-bridge.

**Comment by zappalag** [comment]
I installed the latest version of ha-bridge.  It works a lot better!! I still get some random errors, but they are warnings now and the app no longer crashes.  Thank you for the help!
