### ISSUE TITLE
Can you help with this error?

### ISSUE THREAD

**Issue by lemrock** [bwssytems/ha-bridge#689]
When I run this command line:
$ sudo /usr/bin/java -jar -Dserver.port=8080 -Dconfig.file=/home/pi/habridge/data/habridge1.config -Dupnp.device.db=/home/pi/data/device1.db /home/pi/habridge/ha-bridge-4.5.6.jar

I get this and the HA Bridge fails:
2017-07-07 02:13:04,849 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.6) starting....
2017-07-07 02:13:04,960 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /home/pi/habridge/data/habridge1.config
Exception in thread "main" java.lang.NullPointerException
	at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)

**Comment by bwssytems** [comment]
Does this issue still occur? Seems I took too long to repsond on this and you have other questions as you have it running currently.

**Comment by lemrock** [comment]
I believe I should have closed this issue. Things are resolved.
