### ISSUE TITLE
HAbridge and Home Assistant Error log

### ISSUE THREAD

**Issue by fefris** [bwssytems/ha-bridge#728]
Hi there

Get the following error in Home Assistant when i control my Milights configured in HABridge. The lights still work but the error seems to stop the automation. Any suggestions? it looks to me like that Home assistant expects a responce for HABridge it never gets and stops the automation proceeding>?

2017-08-22` 21:19:35 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 181, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 1025, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/light/__init__.py", line 281, in async_handle_light_service
    yield from light.async_turn_off(**params)
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/light/hue.py", line 452, in turn_off
    self._command_func(self.light_id, command)
  File "/usr/lib/python3.6/site-packages/phue.py", line 898, in set_light
    converted_light) + '/state', data))
  File "/usr/lib/python3.6/site-packages/phue.py", line 667, in request
    return json.loads(response.decode('utf-8'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 81 (char 80)

**Comment by bwssytems** [comment]
If you could look in the ha-bridge log and see if there is an associated error. Otherwise I won't have any ideas.

**Comment by fefris** [comment]
nope, all i get in HAbridge is this: but the lights work, this i get everytime i call the lights via HAbridge from Home assistant at the same time i get the errors in Home Assistant.


Udp Call to be presented as udp://<ip_address>:<port>/payload, format of request unknown: | com.bwssystems.HABridge.plugins.udp.UDPHome
-- | --

**Comment by bwssytems** [comment]
Please post your device,db, Thanks.

**Comment by fefris** [comment]
[device.db.txt](https://github.com/bwssytems/ha-bridge/files/1256712/device.db.txt)

attached

**Comment by bwssytems** [comment]
I am looking into this

**Comment by bwssytems** [comment]
It seems the device `TV Room Lights` has an empty second device call for on and off which causes the error. All other devices seem to work properly in my tests.

**Comment by bwssytems** [comment]
Did you fix your device config?
