### ISSUE TITLE
problem when Run on Android Phone

### ISSUE THREAD

**Issue by alwinzh** [bwssytems/ha-bridge#741]
I have succesfully run Ha-bridge on Windows 10. Now I want to run it on an old Android Phone.
I have followed the introduction of the Wiki Run on Android Phone ([https://github.com/bwssytems/ha-bridge/wiki/Run-on-Android-Phone](https://github.com/bwssytems/ha-bridge/wiki/Run-on-Android-Phone))
I have use Linux deploy installed a Ubuntu.
But at last step when i lunch the ha-bridge-4.5.6.jar, there is an error. The information is below. Is there anyone know what should I do to solve this. Thanks in advance.

> android@localhost:~$ java -jar /home/android/habridge/ha-bridge-4.5.6.jar
2017-09-06 22:59:44,012 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.6) starting....
2017-09-06 22:59:44,202 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from system properties
2017-09-06 22:59:44,237 [main] INFO  com.bwssystems.HABridge.BridgeSettings - Adding 192.168.50.206 as our default upnp config address.
2017-09-06 22:59:44,243 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2017-09-06 22:59:45,030 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2017-09-06 22:59:45.151:INFO::Thread-0: Logging initialized @3699ms
2017-09-06 22:59:45,690 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - Initializing UDP response Socket...
2017-09-06 22:59:45,703 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - UDP response Seocket initialized to: 50000
2017-09-06 22:59:45,725 [main] INFO  com.bwssystems.HABridge.plugins.harmony.HarmonyHome - Harmony Home created. No Harmony devices configured.
2017-09-06 22:59:45,740 [main] INFO  com.bwssystems.HABridge.plugins.NestBridge.NestHome - Nest Home created. No Nest configured.
2017-09-06 22:59:45,748 [main] INFO  com.bwssystems.HABridge.plugins.hue.HueHome - Hue passthru Home created. No Hue passtrhu systems configured.
2017-09-06 22:59:45,756 [main] INFO  com.bwssystems.HABridge.plugins.hal.HalHome - HAL Home created. No HAL devices configured.
2017-09-06 22:59:45,763 [main] INFO  com.bwssystems.HABridge.plugins.mqtt.MQTTHome - MQTT Home created. No MQTT Clients configured.
2017-09-06 22:59:45,792 [main] INFO  com.bwssystems.HABridge.plugins.hass.HassHome - HomeAssistant Home created. No HomeAssistants configured.
2017-09-06 22:59:45,799 [main] INFO  com.bwssystems.HABridge.plugins.exec.CommandHome - Command Home for system program execution created.
2017-09-06 22:59:45,836 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2017-09-06 22:59:45,848 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:80
2017-09-06 22:59:45.891:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2017-09-06 22:59:46,274 [Thread-0] ERROR spark.webserver.JettySparkServer - ignite failed
java.net.SocketException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:326)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:384)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at spark.webserver.JettySparkServer.ignite(JettySparkServer.java:131)
	at spark.SparkInstance.lambda$init$0(SparkInstance.java:341)
	at java.lang.Thread.run(Thread.java:745)

**Comment by alwinzh** [comment]
anybody any idea？

**Comment by bwssytems** [comment]
So the error says you do not have permission to open port 80 on your device. Not sure how you are starting the ha-bridge, but either some other application is using port 80 or you need to run this as root as you do not have permission.

**Comment by alwinzh** [comment]
Thank you very much for your reply. The problem have been solved by change the user to root.  Thank you!
