### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/armzilla/ha/SpringbootEntry : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by lamiastella** [bwssytems/ha-bridge#76]
Hi, Can you please help me how to fix it?
pi@raspberrypi:~/hue $ java -jar amazon-echo-bridge-0.2.1.jar --upnp.config.address=192.168.1.102 -server-port=8081
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/armzilla/ha/SpringbootEntry : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:163)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lamiastella** [comment]
http://www.rpiblog.com/2014/03/installing-oracle-jdk-8-on-raspberry-pi.html
