### ISSUE TITLE
home assistant to ha-bridge

### ISSUE THREAD

**Issue by Clermonder** [bwssytems/ha-bridge#783]
2017-11-14 21:14:44,213 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.6) starting....
2017-11-14 21:14:44,263 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /home/pi/habridge/data/habridge.config
2017-11-14 21:14:46,550 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2017-11-14 21:14:46,586 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2017-11-14 21:14:46,652 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - Initializing UDP response Socket...
2017-11-14 21:14:46.652:INFO::Thread-0: Logging initialized @3466ms
2017-11-14 21:14:46,660 [main] WARN  com.bwssystems.HABridge.util.UDPDatagramSender - UDP Response Port is in use, starting loop to find open port for 20 tries - configured port is: 50000
2017-11-14 21:14:46,661 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - UDP response Seocket initialized to: 50001
2017-11-14 21:14:46,668 [main] INFO  com.bwssystems.HABridge.plugins.harmony.HarmonyHome - Harmony Home created. No Harmony devices configured.
2017-11-14 21:14:46,675 [main] INFO  com.bwssystems.HABridge.plugins.NestBridge.NestHome - Nest Home created. No Nest configured.
2017-11-14 21:14:46,677 [main] INFO  com.bwssystems.HABridge.plugins.hue.HueHome - Hue passthru Home created. No Hue passtrhu systems configured.
2017-11-14 21:14:46,681 [main] INFO  com.bwssystems.HABridge.plugins.hal.HalHome - HAL Home created. No HAL devices configured.
2017-11-14 21:14:46,684 [main] INFO  com.bwssystems.HABridge.plugins.mqtt.MQTTHome - MQTT Home created. No MQTT Clients configured.
2017-11-14 21:14:46,687 [main] INFO  com.bwssystems.HABridge.plugins.hass.HassHome - HomeAssistant Home created.
2017-11-14 21:14:46,910 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2017-11-14 21:14:46,915 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 192.168.50.65:80
2017-11-14 21:14:46.924:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2017-11-14 21:14:47,044 [Thread-0] ERROR spark.webserver.JettySparkServer - ignite failed
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:326)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:384)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at spark.webserver.JettySparkServer.ignite(JettySparkServer.java:131)
	at spark.SparkInstance.lambda$init$0(SparkInstance.java:341)
	at java.lang.Thread.run(Thread.java:748)

this is the log

i run ha-bridge on port 80,but my raspberry no other processes use on port 80 except ha-bridge
`root@hassbian:/home/pi/habridge# netstat -tunlp|grep 80   `
`tcp        0      0 192.168.50.65:80      0.0.0.0:*               LISTEN      29146/java   `

what should i do?
thanks

**Comment by bwssytems** [comment]
Did you start another instance of the ha-bridge and not shut it down?

**Comment by Clermonder** [comment]
I don't think so.
I had close all ha-bridge bacause I can't open 192.168.50.65 which  ha-bridge is running.
Then I  start habridge.service ,issue is still exist.

**Comment by bwssytems** [comment]
Well, the error says that the port is in use. and your netstat showed something on that port.
