### ISSUE TITLE
ha-bridge will not start anymore 

### ISSUE THREAD

**Issue by jolandaanne** [bwssytems/ha-bridge#831]
ha-bridge will not start automatically via service or manually via terminal. Worked perfect before reboot.

manual startup with ` /usr/bin/java -jar -Dconfig.file=/etc/systemd/system/data/habridge.config /services/haBridge/ha-bridge-5.0.0.jar`

will show the following messages:

`2017-12-05 19:53:07,016 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v5.0.0) starting....
2017-12-05 19:53:07,073 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /etc/systemd/system/data/habridge.config
2017-12-05 19:53:07,104 [main] WARN  com.bwssystems.HABridge.BridgeSettings - Error reading the file: /etc/systemd/system/data/habridge.config - Does not exist or is not readable. continuing...
2017-12-05 19:53:07,129 [main] INFO  com.bwssystems.HABridge.BridgeSettings - Adding 10.0.0.5 as our default upnp config address.
2017-12-05 19:53:07,134 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2017-12-05 19:53:07,542 [main] INFO  spark.staticfiles.StaticFilesConfiguration - StaticResourceHandler configured with folder = /public
2017-12-05 19:53:07,610 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2017-12-05 19:53:07.829:INFO::Thread-0: Logging initialized @2638ms to org.eclipse.jetty.util.log.StdErrLog
2017-12-05 19:53:08,047 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - Initializing UDP response Socket...
2017-12-05 19:53:08,062 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - UDP response Seocket initialized to: 50000
2017-12-05 19:53:08,078 [main] INFO  com.bwssystems.HABridge.plugins.harmony.HarmonyHome - Harmony Home created. No Harmony devices configured.
2017-12-05 19:53:08,090 [main] INFO  com.bwssystems.HABridge.plugins.NestBridge.NestHome - Nest Home created. No Nest configured.
2017-12-05 19:53:08,096 [main] INFO  com.bwssystems.HABridge.plugins.hue.HueHome - Hue passthru Home created. No Hue passtrhu systems configured.
2017-12-05 19:53:08,102 [main] INFO  com.bwssystems.HABridge.plugins.hal.HalHome - HAL Home created. No HAL devices configured.
2017-12-05 19:53:08,108 [main] INFO  com.bwssystems.HABridge.plugins.mqtt.MQTTHome - MQTT Home created. No MQTT Clients configured.
2017-12-05 19:53:08,114 [main] INFO  com.bwssystems.HABridge.plugins.hass.HassHome - HomeAssistant Home created. No HomeAssistants configured.
2017-12-05 19:53:08,122 [main] INFO  com.bwssystems.HABridge.plugins.exec.CommandHome - Command Home for system program execution created.
2017-12-05 19:53:08,138 [main] INFO  com.bwssystems.HABridge.plugins.http.HTTPHome - Http Home created.
2017-12-05 19:53:08,144 [main] INFO  com.bwssystems.HABridge.plugins.tcp.TCPHome - TCP Home created.
2017-12-05 19:53:08,153 [main] INFO  com.bwssystems.HABridge.plugins.udp.UDPHome - UDP Home created.
2017-12-05 19:53:08,158 [main] INFO  com.bwssystems.HABridge.plugins.vera.VeraHome - Vera Home created. No Veras configured.
2017-12-05 19:53:08,187 [main] INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroHome - Fibaro Home created. No Fibaros configured.
2017-12-05 19:53:08,193 [main] INFO  com.bwssystems.HABridge.plugins.domoticz.DomoticzHome - Domoticz Home created. No Domoticz devices configured.
2017-12-05 19:53:08,198 [main] INFO  com.bwssystems.HABridge.plugins.somfy.SomfyHome - Somfy Home created. No Somfys configured.
2017-12-05 19:53:08,208 [main] INFO  com.bwssystems.HABridge.plugins.lifx.LifxHome - LifxDevice Home created. No LifxDevices configured.
2017-12-05 19:53:08,204 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
2017-12-05 19:53:08,213 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:80
2017-12-05 19:53:08,226 [main] WARN  com.bwssystems.HABridge.dao.DeviceRepository - Error reading the file: data/device.db - Does not exist or is not readable. continuing...
2017-12-05 19:53:08,234 [main] WARN  com.bwssystems.HABridge.dao.GroupRepository - Error reading the file: data/group.db - Does not exist or is not readable. continuing...
2017-12-05 19:53:08.235:INFO:oejs.Server:Thread-0: jetty-9.4.z-SNAPSHOT
2017-12-05 19:53:08,235 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
2017-12-05 19:53:08,360 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
2017-12-05 19:53:09.145:INFO:oejs.AbstractConnector:Thread-0: Started ServerConnector@10b2910{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
Exception in thread "Thread-0" java.lang.InternalError: internal error: SHA-1 not available.
	at sun.security.provider.SecureRandom.init(SecureRandom.java:108)
	at sun.security.provider.SecureRandom.<init>(SecureRandom.java:79)
	at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:198)
	at java.security.SecureRandom.<init>(SecureRandom.java:162)
	at org.eclipse.jetty.server.session.DefaultSessionIdManager.initRandom(DefaultSessionIdManager.java:406)
	at org.eclipse.jetty.server.session.DefaultSessionIdManager.doStart(DefaultSessionIdManager.java:356)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:294)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:226)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.updateBean(ContainerLifeCycle.java:775)
	at org.eclipse.jetty.server.Server.setSessionIdManager(Server.java:635)
	at org.eclipse.jetty.server.session.SessionHandler.doStart(SessionHandler.java:444)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:149)
	at spark.Service.lambda$init$2(Service.java:496)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.NoSuchAlgorithmException: SHA MessageDigest not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.MessageDigest.getInstance(MessageDigest.java:167)
	at sun.security.provider.SecureRandom.init(SecureRandom.java:106)
	... 23 more
`

**Comment by bwssytems** [comment]
This looks to be a Java version issue. Check the version of Java is at least 1.8 'java -version'

**Comment by tuicemen** [comment]
Today I rebooted (Windows10) and it appeared the bridge failed to load.
Opening the web UI I discovered all devices were no longer there. 
An attempt to load a back up did not even take. 
The issue was my antivirus program. I solved this by adding an exclusion for the folder the bridge was located in.

**Comment by jolandaanne** [comment]
I removed Java with `apt-get -remove ..` and reinstalled it. Now ha-bridge is working again.

**Comment by bwssytems** [comment]
Yep, sounds good. Closing
