### ISSUE TITLE
error with HTML device

### ISSUE THREAD

**Issue by OskarBrink** [bwssytems/ha-bridge#840]
I have installed habridge on a RPI. After install I only added a new HTML device.
All fine, but when I use on or off button to test I get an error message. I've tried to reinstall and also with different versions (4.5.6 as well as 5.0.0).

2017-12-09 21:01:42.964:INFO:oejs.AbstractConnector:Thread-0: Started ServerConnector@1599816{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2017-12-09 21:01:42.972:INFO:oejs.Server:Thread-0: Started @22865ms
2017-12-09 21:01:42,983 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Description xml service started....
2017-12-09 21:01:43,083 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
2017-12-09 21:01:43,096 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener running and ready....
2017-12-09 21:02:36,041 [qtp10675269-8] ERROR spark.http.matching.GeneralError -
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
        at com.google.gson.Gson.fromJson(Gson.java:891)
        at com.google.gson.Gson.fromJson(Gson.java:844)
        at com.google.gson.Gson.fromJson(Gson.java:793)
        at com.google.gson.Gson.fromJson(Gson.java:765)
        at com.bwssystems.HABridge.plugins.http.HTTPHome.deviceHandler(HTTPHome.java:82)
        at com.bwssystems.HABridge.hue.HueMulator.changeState(HueMulator.java:1236)
        at com.bwssystems.HABridge.hue.HueMulator.lambda$39(HueMulator.java:443)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        ... 26 common frames omitted

**Comment by bwssytems** [comment]
I believe you have special characters in your url that are being interpreted in the json parser that is used for the device details. Look at your url and escape any special characters.

**Comment by OskarBrink** [comment]
This is my URL: http://192.168.1.24/api/manager/devices/device/8e4be87a-cbe2-4285-9572-d27d53ed2387/state

How would I escape the special characters with this?

**Comment by bwssytems** [comment]
Ahh, are you setting headers? That is the line that seems to cause the error.

**Comment by OskarBrink** [comment]
This is what I have in the header (I replaced all numbers with zeros): 
{"name":"Authorization","value":"bearer f00e00000000d000000bd0000ffc00eb0dfbdf00"}

**Comment by bwssytems** [comment]
Ahh, you will need to put '\"' in place of '"'.

**Comment by OskarBrink** [comment]
double / single quotes? (to me this seems to be the same

**Comment by bwssytems** [comment]
Sorry, updated it look at the previous post again.

**Comment by OskarBrink** [comment]
I am sorry can you make the edit? I cannot follow you.
{\"name\":\"Authorization\",\"value\":\"bearer f00e00000000d000000bd0000ffc00eb0dfbdf00\"} ...??

**Comment by OskarBrink** [comment]
where do I put the \ ?

**Comment by OskarBrink** [comment]
in front of all quotes?

**Comment by bwssytems** [comment]
It should look like this:

```{\"name\":\"Authorization\",\"value\":\"bearer f00e00000000d000000bd0000ffc00eb0dfbdf00\"}```

**Comment by OskarBrink** [comment]
ok tried, but same result. 
"{\"name\":\"Authorization\",\"value\":\"bearer  f14e41853048d035398bd6754ffc31eb9dfbdf18\"}"

also changed the body with same backslash+quote. same

**Comment by bwssytems** [comment]
I'll try playing around and see what happens.

**Comment by OskarBrink** [comment]
Thank you. Till later

**Comment by quadhammer** [comment]
I hope this is the right thread to post to...
I have a really simple http call:

http://192.168.0.106:8083/?Dragon.On

No headers, body, content etc. Just that.  It's sending to an EventGhost webserver, but since going to 5.0.x it seems it's not getting a correct response.  The event works correctly, but the bridge responds immediately with an error.

Is this something I can disable, or is there something I need to apapt on the webserver end?

Thank you

**Comment by OskarBrink** [comment]
Just found the solution to the issue with help of someone via the Homey forum (thanks to @swtt) by puting square brackets aaround the http header. It now looks like this:
`[{"name":"Authorization","value":"bearer f00e00000000d000000bd0000ffc00eb0dfbdf00"}]`

Problem solved.

**Comment by bwssytems** [comment]
Ahh, yes sorry, that field is a list. Should have caught that.
