### ISSUE TITLE
Cannot add device in ha bridge.

### ISSUE THREAD

**Issue by UserNAMEPersonThingy** [bwssytems/ha-bridge#867]
When I try to add a device in ha-bridge I get always get - "Add new Device Error: undefined with status: Server Error - 500". This is with the latest version of ha bridge. The weird thing is that I can add devices with version 2 of ha bridge. I am running ha bridge on my mac. Here is the error in my log:

Time | Level | Message | Component
-- | -- | -- | --
01-06-2018 11:52:03.351 | ERROR |   | spark.http.matching.GeneralError

**Comment by bwssytems** [comment]
Will need the output of the complete log from the command line. Also, which version exactly were you referencing?

**Comment by UserNAMEPersonThingy** [comment]
I am using version 5.1.0. Here is my log from the terminal when I first startup ha-bridge: 

`2018-01-07 09:51:19,989 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v5.1.0) starting....
2018-01-07 09:51:19,997 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
2018-01-07 09:51:20,059 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2018-01-07 09:51:20,068 [main] INFO  spark.staticfiles.StaticFilesConfiguration - StaticResourceHandler configured with folder = /public
2018-01-07 09:51:20,074 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2018-01-07 09:51:20,090 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - Initializing UDP response Socket...
2018-01-07 09:51:20,097 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - UDP response Seocket initialized to: 50000
2018-01-07 09:51:20,101 [main] INFO  com.bwssystems.HABridge.plugins.harmony.HarmonyHome - Harmony Home created.
2018-01-07 09:51:20.129:INFO::Thread-0: Logging initialized @518ms to org.eclipse.jetty.util.log.StdErrLog
2018-01-07 09:51:20,194 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
2018-01-07 09:51:20,196 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:80
2018-01-07 09:51:20.200:INFO:oejs.Server:Thread-0: jetty-9.4.z-SNAPSHOT
2018-01-07 09:51:20.240:INFO:oejs.session:Thread-0: DefaultSessionIdManager workerName=node0
2018-01-07 09:51:20.240:INFO:oejs.session:Thread-0: No SessionScavenger set, using defaults
2018-01-07 09:51:20.242:INFO:oejs.session:Thread-0: Scavenging every 600000ms
2018-01-07 09:51:20.284:INFO:oejs.AbstractConnector:Thread-0: Started ServerConnector@31ddef79{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2018-01-07 09:51:20.285:INFO:oejs.Server:Thread-0: Started @675ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/Users/User/ha-bridge/ha-bridge-5.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-01-07 09:51:20,540 [main] INFO  com.bwssystems.HABridge.plugins.harmony.HarmonyServer - setup initiated ....
2018-01-07 09:51:22,207 [main] INFO  com.bwssystems.HABridge.plugins.harmony.HarmonyServer - activity changed: [-1] PowerOff
2018-01-07 09:51:22,208 [main] INFO  com.bwssystems.HABridge.plugins.NestBridge.NestHome - Nest Home created. No Nest configured.
2018-01-07 09:51:22,209 [main] INFO  com.bwssystems.HABridge.plugins.hue.HueHome - Hue passthru Home created. No Hue passtrhu systems configured.
2018-01-07 09:51:22,210 [main] INFO  com.bwssystems.HABridge.plugins.hal.HalHome - HAL Home created. No HAL devices configured.
2018-01-07 09:51:22,210 [main] INFO  com.bwssystems.HABridge.plugins.mqtt.MQTTHome - MQTT Home created. No MQTT Clients configured.
2018-01-07 09:51:22,211 [main] INFO  com.bwssystems.HABridge.plugins.hass.HassHome - HomeAssistant Home created. No HomeAssistants configured.
2018-01-07 09:51:22,211 [main] INFO  com.bwssystems.HABridge.plugins.homewizard.HomeWizardHome - HomeWizard Home created. No HomeWizard gateways configured.
2018-01-07 09:51:22,212 [main] INFO  com.bwssystems.HABridge.plugins.exec.CommandHome - Command Home for system program execution created.
2018-01-07 09:51:22,212 [main] INFO  com.bwssystems.HABridge.plugins.http.HTTPHome - Http Home created.
2018-01-07 09:51:22,213 [main] INFO  com.bwssystems.HABridge.plugins.tcp.TCPHome - TCP Home created.
2018-01-07 09:51:22,213 [main] INFO  com.bwssystems.HABridge.plugins.udp.UDPHome - UDP Home created.
2018-01-07 09:51:22,213 [main] INFO  com.bwssystems.HABridge.plugins.vera.VeraHome - Vera Home created. No Veras configured.
2018-01-07 09:51:22,214 [main] INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroHome - Fibaro Home created. No Fibaros configured.
2018-01-07 09:51:22,214 [main] INFO  com.bwssystems.HABridge.plugins.domoticz.DomoticzHome - Domoticz Home created. No Domoticz devices configured.
2018-01-07 09:51:22,215 [main] INFO  com.bwssystems.HABridge.plugins.somfy.SomfyHome - Somfy Home created. No Somfys configured.
2018-01-07 09:51:22,216 [main] INFO  com.bwssystems.HABridge.plugins.lifx.LifxHome - LifxDevice Home created. No LifxDevices configured.
2018-01-07 09:51:22,221 [main] WARN  com.bwssystems.HABridge.dao.GroupRepository - Error reading the file: data/group.db - Does not exist or is not readable. continuing...
2018-01-07 09:51:22,221 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
2018-01-07 09:51:22,232 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
2018-01-07 09:51:22,241 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Description xml service started....
2018-01-07 09:51:22,247 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
2018-01-07 09:51:22,249 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener running and ready....`

Here is when I try to add a device:
`2018-01-07 09:52:42.524:WARN:oejs.HttpChannel:qtp864221550-32: /api/devices
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.bwssystems.HABridge.dao.DeviceRepository.save(DeviceRepository.java:185)
	at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.lambda$2(DeviceResource.java:144)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: 
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.bwssystems.HABridge.dao.DeviceRepository.save(DeviceRepository.java:185)
	at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.lambda$2(DeviceResource.java:144)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.base/java.lang.Thread.run(Thread.java:844)
2018-01-07 09:52:42,530 [qtp864221550-32] ERROR spark.http.matching.GeneralError - 
java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
	at java.base/java.lang.String.substring(String.java:1885)
	at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.lambda$2(DeviceResource.java:88)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:358)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by bwssytems** [comment]
Ahh, it seems you are using Java 9. Either revert to Java 8 or review this issue #854

**Comment by UserNAMEPersonThingy** [comment]
I downgraded to Java 8 and it worked. Thanks.
