### ISSUE TITLE
Unable to start habridge on openelec: Cannot assign requested address

### ISSUE THREAD

**Issue by haranewbie** [bwssytems/ha-bridge#935]
I must preface this by stating that I'm very much a novice when it comes to this stuff.
So, here it is: I had received a raspberry pi with openelec and habridge installed. Recently, I tried using this setup with the Gen 2 Echo but it failed. So I figured if I update the habridge to the latest version it will work but since updating I am unable to start up habridge.
I get the following error
> com.bwssystems.HABridge.HABridge - Could not start ha-bridge webservice on port [80] due to: Cannot assign requested address

I've tried using lsof -i :80 but it doesn't list anything.

Here is the full log

> 2017-01-11 14:12:22,093 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge startup sequence...
2017-01-11 14:12:22,152 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /storage/data/habridge.config
2017-01-11 14:12:22,734 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v5.2.1) initializing....
2017-01-11 14:12:23,100 [main] INFO  spark.staticfiles.StaticFilesConfiguration - StaticResourceHandler configured with folder = /public
2017-01-11 14:12:23,175 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2017-01-11 14:12:23,354 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - Initializing UDP response Socket...
2017-01-11 14:12:23,372 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - UDP response Socket initialized to: 50000
2017-01-11 14:12:23,395 [main] INFO  com.bwssystems.HABridge.plugins.http.HTTPHome - HTTP Home created.
2017-01-11 14:12:23.390:INFO::Thread-0: Logging initialized @4326ms to org.eclipse.jetty.util.log.StdErrLog
2017-01-11 14:12:23,417 [main] INFO  com.bwssystems.HABridge.plugins.harmony.HarmonyHome - Harmony Home created. No Harmony devices configured.
2017-01-11 14:12:23,423 [main] INFO  com.bwssystems.HABridge.plugins.NestBridge.NestHome - Nest Home created. No Nest configured.
2017-01-11 14:12:23,427 [main] INFO  com.bwssystems.HABridge.plugins.hue.HEFFECTENGINE INFO: effect finished
 No Hue passtrhu systems configured.
2017-01-11 14:12:23,437 [main] INFO  com.bwssystems.HABridge.plugins.hal.HalHome - HAL Home created. No HAL devices configured.
2017-01-11 14:12:23,442 [main] INFO  com.bwssystems.HABridge.plugins.mqtt.MQTTHome - MQTT Home created. No MQTT Clients configured.
2017-01-11 14:12:23,448 [main] INFO  com.bwssystems.HABridge.plugins.hass.HassHome - HomeAssistant Home created. No HomeAssistants configured.
2017-01-11 14:12:23,453 [main] INFO  com.bwssystems.HABridge.plugins.homewizard.HomeWizardHome - HomeWizard Home created. No HomeWizard gateways configured.
2017-01-11 14:12:23,457 [main] INFO  com.bwssystems.HABridge.plugins.exec.CommandHome - Command Home for system program execution created.
2017-01-11 14:12:23,461 [main] INFO  com.bwssystems.HABridge.plugins.tcp.TCPHome - TCP Home created.
2017-01-11 14:12:23,469 [main] INFO  com.bwssystems.HABridge.plugins.udp.UDPHome - UDP Home created.
2017-01-11 14:12:23,473 [main] INFO  com.bwssystems.HABridge.plugins.vera.VeraHome - Vera Home created. No Veras configured.
2017-01-11 14:12:23,477 [main] INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroHome - Fibaro Home created. No Fibaros configured.
2017-01-11 14:12:23,482 [main] INFO  com.bwssystems.HABridge.plugins.domoticz.DomoticzHome - Domoticz Home created. No Domoticz devices configured.
2017-01-11 14:12:23,487 [main] INFO  com.bwssystems.HABridge.plugins.somfy.SomfyHome - Somfy Home created. No Somfys configured.
2017-01-11 14:12:23,503 [main] INFO  com.bwssystems.HABridge.plugins.lifx.LifxHome - LifxDevice Home created. No LifxDevices configured.
2017-01-11 14:12:23,509 [main] INFO  com.bwssystems.HABridge.plugins.openhab.OpenHABHome - OpenHAB Home created. No OpenHABs configured.
2017-01-11 14:12:23,514 [main] INFO  com.bwssystems.HABridge.plugins.fhem.FHEMHome - FHEM Home created. No FHEMs configured.
2017-01-11 14:12:23,542 [main] INFO  com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome - Broadlink Home created. No Broadlinks configured.
2017-01-11 14:12:23,596 [main] WARN  com.bwssystems.HABridge.dao.GroupRepository - Error reading the file: data/group.db - Does not exist or is not readable. continuing...
2017-01-11 14:12:23,597 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
2017-01-11 14:12:23,746 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
2017-01-11 14:12:23,778 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
2017-01-11 14:12:23,789 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 192.168.1.7:80
2017-01-11 14:12:23.806:INFO:oejs.Server:Thread-0: jetty-9.4.z-SNAPSHOT
2017-01-11 14:12:24.000:INFO:oejs.session:Thread-0: DefaultSessionIdManager workerName=node0
2017-01-11 14:12:24.004:INFO:oejs.session:Thread-0: No SessionScavenger set, using defaults
2017-01-11 14:12:24.024:INFO:oejs.session:Thread-0: Scavenging every 600000ms
2017-01-11 14:12:24,082 [Thread-0] ERROR com.bwssystems.HABridge.HABridge - Could not start ha-bridge webservice on port [80] due to: Cannot assign requested address

How do I fix this..?
 EDIT: I tried changing to the old version but I'm still getting the same issue

> 2017-01-11 14:12:22,572 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.5.1) starting....
2017-01-11 14:12:22,608 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /storage/data/habridge.config
2017-01-11 14:12:23,038 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge initializing....
2017-01-11 14:12:23,109 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2017-01-11 14:12:23.605:INFO::Thread-0: Logging initialized @4244ms
2017-01-11 14:12:23,652 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
2017-01-11 14:12:23,712 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
2017-01-11 14:12:23,735 [main] INFO  com.bwssystems.util.UDPDatagramSender - Initializing UDP response Seocket...
2017-01-11 14:12:23,748 [main] INFO  com.bwssystems.util.UDPDatagramSender - UDP response Seocket initialized to: 50000
2017-01-11 14:12:24,352 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
2017-01-11 14:12:24,363 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 192.168.1.7:80
2017-01-11 14:12:24.388:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2017-01-11 14:12:24,608 [Thread-0] ERROR spark.webserver.JettySparkServer - ignite failed
java.net.BindEEFFECTENGINE INFO: effect finished
ddress
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.Net.bind(Net.java:428)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:326)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:384)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at spark.webserver.JettySparkServer.ignite(JettySparkServer.java:131)
	at spark.SparkInstance.lambda$init$0(SparkInstance.java:341)
	at spark.SparkInstance$$Lambda$2/3797790.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bwssytems** [comment]
So, you need root privileges to bind to port 80.

**Comment by haranewbie** [comment]
From what I've seen, openelec has root previleges enabled by default..

**Comment by haranewbie** [comment]
I managed to get it working again. I forcibly changed the server ip address and port by starting the service from the command line. After that I was able to revert to port 80.
