### ISSUE TITLE
pairing problem

### ISSUE THREAD

**Issue by Kat-CeDe** [bwssytems/ha-bridge#937]
Hi,
I have HA-Bridge running since last 4.x and it was working quite good with Samsung Smartthings, Logitech Harmony and OpenHab2.0.2 since I updated to HA-Bridge 5.2 I cannot pair neither any more.

What I found out is that creating a new user seems to work quite nicely but Harmony, SmartThings and OpenHab2 never reported OK.

In the logfile there is always an Error after asking for a light list

OpenHab2:
`2018-03-26 09:44:18,261 [qtp143525053-12] INFO  com.bwssystems.HABridge.hue.HueMulator - Traceupnp: hue lights list requested by user: 8cc70a980cda45939a5712fd2b9cc5b6 from address: 192.168.178.3
2018-03-26 09:44:18,270 [qtp143525053-12] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
	at com.bwssystems.HABridge.plugins.hue.HueHome.getHueDeviceInfo(HueHome.java:88)
	at com.bwssystems.HABridge.hue.HueMulator.lightsListHandler(HueMulator.java:884)
	at com.bwssystems.HABridge.hue.HueMulator.getFullState(HueMulator.java:995)
	at com.bwssystems.HABridge.hue.HueMulator.lambda$33(HueMulator.java:387)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)     `

Harmony:
`2018-03-26 09:59:03,206 [qtp143525053-14] INFO  com.bwssystems.HABridge.hue.HueMulator - Traceupnp: hue lights list requested by user: da758c69fa1c4058b479c38ad3afadf1 from address: 192.168.178.37
2018-03-26 09:59:03,207 [qtp143525053-14] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
	at com.bwssystems.HABridge.plugins.hue.HueHome.getHueDeviceInfo(HueHome.java:88)
	at com.bwssystems.HABridge.hue.HueMulator.lightsListHandler(HueMulator.java:884)
	at com.bwssystems.HABridge.hue.HueMulator.lambda$23(HueMulator.java:293)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)    `

SmartThings:
`2018-03-26 09:44:30,087 [qtp143525053-14] INFO  com.bwssystems.HABridge.hue.HueMulator - Traceupnp: hue lights list requested by user: a4d5e9dad44244028bc26e447a7d996c from address: 192.168.178.50
2018-03-26 09:44:30,089 [qtp143525053-14] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
	at com.bwssystems.HABridge.plugins.hue.HueHome.getHueDeviceInfo(HueHome.java:88)
	at com.bwssystems.HABridge.hue.HueMulator.lightsListHandler(HueMulator.java:884)
	at com.bwssystems.HABridge.hue.HueMulator.lambda$23(HueMulator.java:293)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)  `

It might be due to a quite long list of HA-Bridge devices which is 101 at the moment. HA-Bridge is running on a x64-QNap-NAS.

Any ideas? 

Ralf

**Comment by bwssytems** [comment]
That error shows that when it is trying to get a certain device into the list, it is tagged as a Hue passthru device. So it is trying to go to the Hue utilities to query it. Do you have any devices that are Hue passthru devices?

**Comment by bwssytems** [comment]
Any update on this
